### ISSUE TITLE
Calling Code in a ComAddin from VBA

### ISSUE THREAD

**Issue by maliutin** [NetOfficeFw/NetOffice#11]
Hi All

VSTO Add-in allows to call methods from VBA. [Here](https://msdn.microsoft.com/en-us/library/bb608614.aspx) the example how we can do it with VSTO.

How can I do same with NetOffice?

**Comment by jozefizso** [comment]
You can expose COM class from your NetOffice add-in and call it from VBA as any COM/ActiveX component.

Don't forget to register the COM class from you assembly so it is available to other applications.

**Comment by maliutin** [comment]
@jozefizso 
But in this case I need to get the reference to current .NET COMAddin instance.
I see only one way, it is create a static field.

Is there a practice such as RequestComAddInAutomationService in VSTO to get a reference to current COMAddin of .NET instance?

**Comment by jozefizso** [comment]
I think you should be able to instantiate any COM component in VBA and call its methods.

The RequestComAddInAutomationService is proprietary for VSTO implementation. NetOffice does not have that concept. But I think you can implement something similar in your addin to get references to your COM objects in addin.

**Comment by maliutin** [comment]
Hi @jozefizso 

I see that last build [v1.7.4.3](https://github.com/NetOfficeFw/NetOffice/releases/tag/v1.7.4.3) contains the solution for this issue. Thanks.
Does it work only with Word as in the [example](https://github.com/NetOfficeFw/NetOffice/blob/v1.7.4.3/Examples/Word/C%23/NetOffice%20COMAddin%20Examples/06%20Custom%20Addin%20Object/Addin.cs)?

**Comment by jozefizso** [comment]
Calling COM components will work in each MS Office add-in.
