### ISSUE TITLE
ProgId Not Found: Office 2016 Click To Run Install

### ISSUE THREAD

**Issue by Spinarooni** [NetOfficeFw/NetOffice#14]
I have a workstation that has Office 2016 installed via the Office Deployment Tool (ODT) and my application throws an error when trying to do a mail merge via MS Word 2016:

`progId not found. Word.Application
`

As far as I can tell there is no ProgID registry key entered for MS Word with the ODT install.  Any ideas?

**Comment by jozefizso** [comment]
Hi,
you should contact Microsoft Support if you have issues with MS Office deployed with their Office Deployment Tool.

**Comment by Spinarooni** [comment]
We did a reinstall of the Office suite and that fixed the issue.
