### ISSUE TITLE
Setting the color of databar

### ISSUE THREAD

**Issue by nobisheikh** [NetOfficeFw/NetOffice#15]
Hello,

I am in process of converting my code from the excel interop to netoffice. I noticed that with excel interop I was able to set the databar fill color with the following code:

            Databar db = (Databar)range.FormatConditions.AddDatabar();
            db.BarColor = ColorTranslator.ToOle(Color.Green);

However it seems like the BarColor is a ready only property in netoffice, any particular reason for that?

Thanks,

- Nabeel

**Comment by jozefizso** [comment]
`Databar.BarColor` property is documented as read-only.

https://msdn.microsoft.com/EN-US/library/microsoft.office.interop.excel.databar.barcolor.aspx

**Comment by nobisheikh** [comment]
Interesting, I have been using it to set a custom color for at least couple years now using the interop.

Thanks,

- Nabeel


On Oct 17, 2017, at 6:45 AM, Jozef Izso <notifications@github.com<mailto:notifications@github.com>> wrote:


Databar.BarColor property is documented as read-only.

https://msdn.microsoft.com/EN-US/library/microsoft.office.interop.excel.databar.barcolor.aspx<https://urldefense.proofpoint.com/v2/url?u=https-3A__msdn.microsoft.com_EN-2DUS_library_microsoft.office.interop.excel.databar.barcolor.aspx&d=DwMCaQ&c=birp9sjcGzT9DCP3EIAtLA&r=R4msGv38p_6ZyC4HtMv6SwjacYqH5GBHsfnYfkBQiD8&m=_Z3VIJsgAyEeJ-0yJYYgSxC-ZKjYhqOUBxi6TihbsHg&s=uz-xXwpZXbrW-d30U5yWQk7-IzwpEC35HqEsYIlFBxE&e=>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_NetOfficeFw_NetOffice_issues_15-23issuecomment-2D337192439&d=DwMCaQ&c=birp9sjcGzT9DCP3EIAtLA&r=R4msGv38p_6ZyC4HtMv6SwjacYqH5GBHsfnYfkBQiD8&m=_Z3VIJsgAyEeJ-0yJYYgSxC-ZKjYhqOUBxi6TihbsHg&s=pLtMESoh60vtb3Oji25NSC9gTcFj2P1IGjGoZMjS1z4&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABo8riAfPLk7BmimCFqQyi6UC-5FuH7npzks5stIU2gaJpZM4P7lJu&d=DwMCaQ&c=birp9sjcGzT9DCP3EIAtLA&r=R4msGv38p_6ZyC4HtMv6SwjacYqH5GBHsfnYfkBQiD8&m=_Z3VIJsgAyEeJ-0yJYYgSxC-ZKjYhqOUBxi6TihbsHg&s=Pi5PcULKKfPWowz_q4-l_erOCbms4LPVEWh7bDytH4g&e=>.

________________________________

This email is intended solely for the recipient. It may contain privileged, proprietary or confidential information or material. If you are not the intended recipient, please delete this email and any attachments and notify the sender of the error.

**Comment by jozefizso** [comment]
The `IDatabase` interface and `Databar` dispatch interface both report that property as getter only in COM API.

Even latest NetOffice library defines this property as getter only.

I'm not sure if Excel interop library calls the setter using private API, but it is not exported in official COM API.

**Comment by jozefizso** [comment]
Neither my `Microsoft.Office.Interop.Excel, Version=15.0.0.0` does define setter for this property.

```
[DispId(2722)]
object BarColor
{
    [DispId(2722), MethodImpl(MethodImplOptions.PreserveSig | MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
    [return: MarshalAs(UnmanagedType.IDispatch)]
    get;
}
```
![screenshot_101717_031405_pm](https://user-images.githubusercontent.com/287778/31666843-ecd5e18a-b34d-11e7-8e08-b283813716a1.jpg)

**Comment by nobisheikh** [comment]
You’re correct. I looked at my project and it does says it’s read only. However not sure how the code compiles, runs and set’s the color of the bar. In any case I can live without it.

[cid:image002.jpg@01D3472C.894AF340]

Thanks.

- Nabeel

**Comment by jozefizso** [comment]
It's dynamic object - that's why it compiles. If this code actually works at runtime, then there is private setter on that COM object.

**Comment by jozefizso** [comment]
But your code is changing the `FormatColor.Color` property with has getter and setter.
