### ISSUE TITLE
Word Document Print Preview

### ISSUE THREAD

**Issue by netoffice-bot** [NetOfficeFw/NetOffice#163]
<img src="https://avatars.githubusercontent.com/u/30236365?s=96" align="left" width="48" height="48" /> <strong>Issue by <a href="https://www.codeplex.com/site/users/view/Legolash2o" rel="author">Legolash2o</a></strong>
<em datetime="2016-01-25T11:01:42">Mon, 25 Jan 2016 11:01:42 GMT</em>
_Originally opened as https://netoffice.codeplex.com/workitem/22149_

----

I'm currently using NetOffice to create a word document and it works beautifully. However, the newDocument.PrintPreview() doesn't actually do anything. I was expecting it to popup a window and show a preview of the page.

PrintOut() works fine though.

**Comment by jozefizso** [comment]
This code will display the print preview window - using NetOffice 1.7.4.3 and MS Office 2016.

```csharp
using (var word = new NetOffice.WordApi.Application())
{
    word.Visible = true;

    var document = word.Documents.Open(@"Print.docx");
    document.ActiveWindow.Activate();
    document.PrintPreview();

    Thread.Sleep(TimeSpan.FromSeconds(10));

    word.Quit(false);
}
```
