### ISSUE TITLE
Excel FormatConditions do not resolve to derived types

### ISSUE THREAD

**Issue by netoffice-bot** [NetOfficeFw/NetOffice#167]
<img src="https://avatars.githubusercontent.com/u/30236365?s=96" align="left" width="48" height="48" /> <strong>Issue by <a href="https://www.codeplex.com/site/users/view/hotn" rel="author">hotn</a></strong>
<em datetime="2016-02-24T18:46:51">Wed, 24 Feb 2016 18:46:51 GMT</em>
_Originally opened as https://netoffice.codeplex.com/workitem/22178_

----

Using NetOffice, all items contained in ExcelApi.FormatConditions resolve to be of type ExcelApi.FormatCondition. Depending on what type of conditioning has been applied, the items should be of varying types, such as Top10 or Databar (see <a href="https://msdn.microsoft.com/en-us/library/microsoft.office.interop.excel.xlformatconditiontype.aspx" rel="nofollow">https://msdn.microsoft.com/en-us/library/microsoft.office.interop.excel.xlformatconditiontype.aspx</a> for format condition types).

A workaround for this is to do something like:
var defaultCondition = Application.ActiveSheet.Range("A1").FormatConditions[1];
var typedCondition = new Top10(defaultCondition);
//typedCondition.Rank is now available, while defaultCondition.Rank throws an exception

The specific format condition types should inherit from FormatCondition and FormatConditions[index] should automatically resolve the type and return the derived type object.

**Comment by jozefizso** [comment]
You must manually convert the returned object to the correct type. Even if NetOffice wrapped this code and instantiated concrete **FormatConditions** subclasses, you would have to cast the objects as the return type of this indexer will always be `FormatConditions` class.
