### ISSUE TITLE
Trusted publisher signing

### ISSUE THREAD

**Issue by netoffice-bot** [NetOfficeFw/NetOffice#169]
<img src="https://avatars.githubusercontent.com/u/30236365?s=96" align="left" width="48" height="48" /> <strong>Issue by <a href="https://www.codeplex.com/site/users/view/forku" rel="author">forku</a></strong>
<em datetime="2016-03-24T17:04:52">Thu, 24 Mar 2016 17:04:52 GMT</em>
_Originally opened as https://netoffice.codeplex.com/workitem/22223_

----

Hi,

I've developed an extension based on NetOffice. My office configuration requires applications to be signed by Trusted Publishers. I tried signing the output DLL with signtool.exe, with a valid certificate, but unfortunately, Office says "There is no digital signature available".

The option can be enabled via: File->Options->Trust Center->Trust Center Settings -> Add-ins -> Require application Add-ins to be signed by Trusted Publisher

What's the appropriate method for signing the DLL? 

It seems that when using VSTO ClickOnce handles the signing, also there's a .manifest file that is created for the DLL, I'm not sure if its required or not but I'm unable to create one for class libraries.

<a href="https://msdn.microsoft.com/en-us/library/bb772096(v=vs.120).aspx" rel="nofollow">https://msdn.microsoft.com/en-us/library/bb772096(v=vs.120).aspx</a>
<a href="https://msdn.microsoft.com/en-us/library/bb386179.aspx" rel="nofollow">https://msdn.microsoft.com/en-us/library/bb386179.aspx</a>
<a href="https://msdn.microsoft.com/en-us/library/che5h906.aspx" rel="nofollow">https://msdn.microsoft.com/en-us/library/che5h906.aspx</a>

**Comment by jozefizso** [comment]
Duplicate of #23
