### ISSUE TITLE
Exception thrown with Visio Page.GetFormulas

### ISSUE THREAD

**Issue by netoffice-bot** [NetOfficeFw/NetOffice#176]
<img src="https://avatars.githubusercontent.com/u/30236365?s=96" align="left" width="48" height="48" /> <strong>Issue by <a href="https://www.codeplex.com/site/users/view/saveenr" rel="author">saveenr</a></strong>
<em datetime="2016-09-04T06:37:30">Sun, 04 Sep 2016 06:37:30 GMT</em>
_Originally opened as https://netoffice.codeplex.com/workitem/22311_

----

I am exploring using NetOffice.Visio for my project VisioAutomation: <a href="https://github.com/saveenr/VisioAutomation" rel="nofollow">https://github.com/saveenr/VisioAutomation</a>

Here's some code which works with Microsoft.Office.Interop.Visio
<pre><code>        // using IVisio = Microsoft.Office.Interop.Visio;
        var app = new IVisio.Application();
        var doc = app.Documents.Add("");
        var page = app.ActivePage;
        var shape = page.DrawRectangle(0, 0, 2, 3);
        shape.Text = "With Microsoft.Office.Interop.Visio";

        var SID_SRCStream = new short[4];
        SID_SRCStream[0] = (short)shape.ID16;
        SID_SRCStream[1] = (short)IVisio.VisSectionIndices.visSectionObject;
        SID_SRCStream[2] = (short)IVisio.VisRowIndices.visRowFill;
        SID_SRCStream[3] = (short)IVisio.VisCellIndices.visFillForegnd;

        System.Array a;
        page.GetFormulasU(SID_SRCStream, out a);
</code></pre>

But the same code throws an exception with NetOffice.Visio (for .NET 4.0)
<pre><code>        // using IVisioNetOffice = NetOffice.VisioApi;
        var app = new IVisioNetOffice.Application();
        var doc = app.Documents.Add("");
        var page = app.ActivePage;
        var shape = page.DrawRectangle(0, 0, 2, 3);
        shape.Text = "With NetOffice";

        var SID_SRCStream = new short[4];
        SID_SRCStream[0] = (short)shape.ID16;
        SID_SRCStream[1] = (short)IVisioNetOffice.Enums.VisSectionIndices.visSectionObject;
        SID_SRCStream[2] = (short)IVisioNetOffice.Enums.VisRowIndices.visRowFill;
        SID_SRCStream[3] = (short)IVisioNetOffice.Enums.VisCellIndices.visFillForegnd;

        object[] a;
        page.GetFormulasU(SID_SRCStream, out a);
</code></pre>

The exception occurs in GetFormulas the inner exception says "{"Type mismatch. (Exception from HRESULT: 0x80020005 (DISP_E_TYPEMISMATCH))"}". 

I suspect the problem is with the second parameter because setformulas seems to work with the same SID_SRCStream.

Any ideas what is wrong in my code?

**Comment by jozefizso** [comment]
Closing as Visio library was removed.
