### ISSUE TITLE
Range.Offset[] does not work

### ISSUE THREAD

**Issue by netoffice-bot** [NetOfficeFw/NetOffice#177]
<img src="https://avatars.githubusercontent.com/u/30236365?s=96" align="left" width="48" height="48" /> <strong>Issue by <a href="https://www.codeplex.com/site/users/view/JBjurstam" rel="author">JBjurstam</a></strong>
<em datetime="2016-09-28T12:27:50">Wed, 28 Sep 2016 12:27:50 GMT</em>
_Originally opened as https://netoffice.codeplex.com/workitem/22312_

----

The indexer .Offset[] does not work as expected. See full code below. I use Excel 2010 and NetOffice for .NET 4.5 obtained as a NuGet package

```csharp
using System;
using Excel = NetOffice.ExcelApi;
using System.IO;

namespace NetOfficeBugs
{
    class Program
    {
       static void Main(string[] args)
        {
            using (var exApp = new Excel.Application())
            {
                Console.WriteLine($"Excel Version: {exApp.Version}");

                var xml = File.ReadAllText("example.xml");

                exApp.Visible = true;

                var workbook = exApp.Workbooks.Add();
                var sheet = (Excel.Worksheet)workbook.Worksheets[1];


                //Uncomment what you want to test
                //OffsetNetOffice(sheet);
                //OffsetUnderlyingObject(sheet);
            }

            Console.WriteLine();
            Console.WriteLine("Done executing!");
            Console.ReadLine();
        }

        private static void OffsetUnderlyingObject(Excel.Worksheet sheet)
        {
            var cell1 = (dynamic)sheet.Cells[5, 5].UnderlyingObject;
            Console.WriteLine($"cell1: {cell1.Address}");

            var cell2 = cell1.Offset[-1, 0];
            Console.WriteLine($"cell2: {cell2.Address}");

            var cell2OtherOverLoad = cell1.Offset[-1];
            Console.WriteLine($"cell2: {cell2OtherOverLoad.Address}");


            /*Output:
               Excel Version: 14.0
               cell1: $E$5
               cell2: $E$4
               cell2: $E$4
            */

        }

        private static void OffsetNetOffice(Excel.Worksheet sheet)
        {
            var cell1 = sheet.Cells[5, 5];
            Console.WriteLine($"cell1: {cell1.Address}");

            var cell2 = cell1.Offset[-1, 0];
            Console.WriteLine($"cell2: {cell2.Address}");

            var cell2OtherOverLoad = cell1.Offset[-1];
            Console.WriteLine($"cell2: {cell2OtherOverLoad.Address}");

            /*Output:
                Excel Version: 14.0
                cell1: $E$5
                cell2: $D$3
                cell2: $E$3
            */
        }
	}
}
```

**Comment by jozefizso** [comment]
This is a tricky bug in how the underlying Excel API is wrapped.

When using `Range` in NetOffice, you can access two different kinds of *Offset* members:

1. `Offset[0,0]` is an indexer into the Range object (calls the `Range._Default(0,0)` method)
2. `Offset(0,0)` is an method which is the same code as called from VBA or when using dynamic object.

The indexer behaves very differently and to achieve the behavior of the dynamic object, you must change calls to `Offset(-1, 0)`.

**Comment by jozefizso** [comment]
This API is quite non-intuitive as there are two different options to call the *Offset* member.

To get the VBA behavior, use the `Range.Offset(row, column)` method.

To keep the compatibility with existing usages of NetOffice library, there is `Range.Offset[row, column]` indexer which has different behavior.

The `Offset(0, 0)` and `Offset[1, 1]` are equivalent as the indexer returns cells shifted by 1. Also `Offset(-1, -1)` and `Offset[0, 0]` will return the same cell.
