### ISSUE TITLE
Worksheet.Range is not an indexer (C#)

### ISSUE THREAD

**Issue by netoffice-bot** [NetOfficeFw/NetOffice#179]
<img src="https://avatars.githubusercontent.com/u/30236365?s=96" align="left" width="48" height="48" /> <strong>Issue by <a href="https://www.codeplex.com/site/users/view/JBjurstam" rel="author">JBjurstam</a></strong>
<em datetime="2016-09-28T12:50:52">Wed, 28 Sep 2016 12:50:52 GMT</em>
_Originally opened as https://netoffice.codeplex.com/workitem/22314_

----

In the standard libraries, Worksheet.Range is implemented as an indexer, but in NetOffice it is a simple method.  This strikes me as weird since .Cells[] and .Offset[] both are indexers, using [] instead of ().

Standard Excel Interop:
<pre><code>var formattingRange = pivotSheet.Range[firstCell, lastCell];</code></pre>

NetOffice:
<pre><code>var formattingRange = pivotSheet.Range(firstCell, lastCell);</code></pre>

I had to edit some 400 instances of this when I converted a project to NetOffice, so I think I'm not the only one who would appreciate support for the .Range[a, b] syntax.

**Comment by jozefizso** [comment]
`Range` is already implemented as a method in NetOffice and this would be a huge breaking change.
