### ISSUE TITLE
Add in project can not start when  VS 2015 without "Run as administrator"

### ISSUE THREAD

**Issue by Linhin** [NetOfficeFw/NetOffice#186]
Hello,
I'm currently developing Addin with VSTO and trying to change to NetOffice. After creating a project with Develop Toolbox, and start project with Visual Studio 2015 (VS2015), VS2015 shows an error: "Cannot unregister assembly "....dll" - access denied. Please make sure you're running the application as administrator. Requested registry access is not allowed". Project can not start.
But when open VS2015 by "Run as administrator" and start project, no error shows up. How can I fix it?

**Comment by maliutin** [comment]
Hello

I suppose you need to check `RegistryLocation` attribute. Maybe you use `RegistrySaveLocation.LocalMachine` value. In this case, you need to have the admins rights to write values into `HKEY_LOCAL_MACHINE`.

You can try `RegistrySaveLocation.CurrentUser` if it suits you.

**Comment by Linhin** [comment]
Thank you, maliutin. I used RegistrySaveLocation.InstallScopeCurrentUser. I changed it to CurrentUser but problem still remain.

**Comment by jozefizso** [comment]
Visual Studio requires you to run it as administrator for the **Register for COM interop** project setting to work correctly.
