### ISSUE TITLE
Way to access RibbonUI xml elements

### ISSUE THREAD

**Issue by Linhin** [NetOfficeFw/NetOffice#187]
Hello,
I'm sorry for stupid question. Is there any way to programmatically access Ribbon elements? I tried Addin.RibbonUI but seem no properties or methods return the elements of RibbonUI that defined in RibbonUI.xml.

**Comment by jozefizso** [comment]
NetOffice does not provide object model API for Ribbon XML.

The Ribbon COM API allows you to invalidate the ribbon state so Office will reload the XML data. You have to manually change the XML though.

https://stackoverflow.com/questions/8510643/how-do-i-enable-disable-my-ribbon-buttons-in-outlook/8522117#8522117

**Comment by Linhin** [comment]
I understand. Thank you for your support.
