### ISSUE TITLE
Is there a way to deploy Addin that does not target to GAC

### ISSUE THREAD

**Issue by Linhin** [NetOfficeFw/NetOffice#188]
Hello,
I read the instruction of deployment at: https://netoffice.codeplex.com/wikipage?title=Tutorial11_DE_CS. But still wonder what should I do if I want to target Addin to another folder (not GAC), example C:\Users\<username>\AppData\Local\AddinName?

**Comment by jozefizso** [comment]
NetOffice supports deployment outside the GAC. Install your assemblies and register the Addin.

**Comment by Linhin** [comment]
Thank you for your support! I will try.
