### ISSUE TITLE
MSI Deployment example (C#) does not work

### ISSUE THREAD

**Issue by Linhin** [NetOfficeFw/NetOffice#189]
I used [Example] MSI Deployment (C#) from Codeplex: http://netoffice.codeplex.com/downloads/get/372516. After successfully install the DeploymentSample Addin. The addin was not loaded when open Excel, it appears in the inactive list of Excel addin.
![image](https://user-images.githubusercontent.com/18644175/34459315-a4a35782-ee1f-11e7-9556-1074cca6afe5.png)
What did I do wrong here?

**Comment by jozefizso** [comment]
I tried to build the sample and run the setup. Sample Excel addin was correctly registered and it is working.

![screenshot_010118_103813_pm](https://user-images.githubusercontent.com/287778/34471255-85d11242-ef44-11e7-9862-440b468c4708.jpg)

**Comment by Linhin** [comment]
I'm sorry for delay response. I don't know why. But I change target director to ProgramFiles for the Addin.dll. And after run regasm/codebase for the Addin.dll. I work perfectly.

**Comment by maliutin** [comment]
Hi @Linhin.

I had the same for Word. I suppose an office add-in works correctly from trusted folder such as "Program Files" or GAC. In other ways, Excel or Word process should be started with admin rights. Now I test my Word add-in from "bin" folder.

**Comment by jozefizso** [comment]
Add-ins can be loaded from any location in default MS Office installation.

In case of enterprise scenarios where administrator locks down MS Office, there may be restrictions on which add-ins are loaded.
