### ISSUE TITLE
Enumerating DAO Recordset Fields throws unable to cast from Field2 to Field

### ISSUE THREAD

**Issue by semenenkov** [NetOfficeFw/NetOffice#19]
Hello,

Getting familiar with your amazing project and have faced with such issue - can not enumerate DAO recordset fields - unable to cast from Field2 to Field. Looked at the code and tried to fix by replacing Field with the base _Field which should work with both Field and Field2 - and it seems to work. For now I've checked only with Office 2013 and 2016/365, going to check later also for 2007 - that's the lowest version I need to support.

Attaching svn patch as text - may be it would be helpful.

[Fields.patch.txt](https://github.com/NetOfficeFw/NetOffice/files/1419876/Fields.patch.txt)

Cheers,
Konstantin

**Comment by jozefizso** [comment]
Fixed in release [v1.7.4.1 (Update 1)](https://github.com/NetOfficeFw/NetOffice/releases/tag/v1.7.4.1%2Bupdate1)
