### ISSUE TITLE
NetOffice.Exceptions.PropertyGetCOMException

### ISSUE THREAD

**Issue by matteshe** [NetOfficeFw/NetOffice#195]
Did you ever experience the Exception NetOffice.Exceptions.PropertyGetCOMException?

I get this for the properties Workbook.Saved or Application.Visible

InnerException Msg: Das aufgerufene Objekt wurde von den Clients getrennt. (Ausnahme von HRESULT: 0x80010108 (RPC_E_DISCONNECTED))
Called Object was disconnected from clients

Any hints on how to prevent this?

**Comment by jozefizso** [comment]
Please, provide more information about you issue.
