### ISSUE TITLE
Unsubscribe (-=) from Excel Worksheet.ChangeEvent does not work 

### ISSUE THREAD

**Issue by Linhin** [NetOfficeFw/NetOffice#196]
After subcribing an object to Worksheet.ChangeEvent of an Excel worksheet: 
worksheet.ChangeEvent += WorksheetChangeHandler;
However unsubcirbe it by -= operator doesn't work, it still remain with ChangeEvent handler. Is there other way to unsubcribe from ChangeEvent.
(Net Office 1.7.4)

**Comment by jozefizso** [comment]
You must retain the `worksheet` object on which you added the event handler to properly remove the handler in the future.
