### ISSUE TITLE
Stream document to client

### ISSUE THREAD

**Issue by ianlivesey** [NetOfficeFw/NetOffice#198]
Hi, I'm trying to use NetOffice.WordApi to retrieve a word document, update a bookmark and then response.write down to the client.
I've done the first 2 parts but can't work out how to convert the document object to a stream to send down to the clients browser.
Do you have any example code c# or vn.net or any advise how to accomplice this task?

Thanks

Ian

**Comment by jozefizso** [comment]
Hi Ian,
you must save the document to the disk and then work with the file/stream as usual.
