### ISSUE TITLE
netoffice  deployed in IIS

### ISSUE THREAD

**Issue by dnamna** [NetOfficeFw/NetOffice#2]
Hi, 
I have integrated the netoffice api in my asp.net web application to convert docx to pdf. 
Running the application from visual studio,the application runs perfectly. 
However, when I deploy my asp.net web application under IIS, document is always null
```
 object returnValue = comObject.InstanceType.InvokeMember(name, BindingFlags.InvokeMethod | BindingFlags.GetProperty, null, comObject.UnderlyingObject, paramsArray, Settings.Default.ThreadCulture);
return value is always null 
```
I have office 2016 installed on my machine and my application is running under framework 3.5. 
Thx,

**Comment by dnamna** [comment]
The below fixed the issue

In the command line put DCOMCNFG
Component Services -> Computers -> My Computer -> DCOM Config
Find "Microsoft Word 97 - 2003 Document" (If it is missing check if your Word is also 64 bit (if your Windows is))
Right click -> Properties
Go To Tab Security and Edit the "Customize" radio buttons so that IIS_IUSRS could have rights for launch and access
Go to Tab Identity and choose "The interactive user"
Apply changes and try again
If all this fails, go also to tab "General" and in "Authentication Level" drop down choose "None".

**Comment by jozefizso** [comment]
Hi @dnamna, please note that running NetOffice from IIS is not supported. Using NetOffice to automate MS Office applications from a Windows Service may require manual changes to permissions and COM+ settings that are not normally granted to Windows services.

Microsoft does not support this scenario, as automation of Office applications is only supported for client applications running in user desktop sessions.
