### ISSUE TITLE
I used is netoffice 1.5.1.2, sometimes WorkbookOpenEvent works before excel window show up...

### ISSUE THREAD

**Issue by szjfhb** [NetOfficeFw/NetOffice#20]
As title, how can i control my process wait until the excel shows?

For my check, maybe it's due to we also have a .XLA add-in in our project. but ANY XLA maybe cause splash wait more than it should.
I'm ready to remove the .XLA, but still want to know does there a way to let splash window dispear & show the excel UI?

case 1: splash block by confirm dialog.
![image](https://user-images.githubusercontent.com/6204704/32361870-5e399f34-c09f-11e7-8148-8e383a5991ca.png)
start excel block here
![image](https://user-images.githubusercontent.com/6204704/32361874-6b80a0de-c09f-11e7-8109-cb6a4b4c1284.png)
after open a new excel instance, before one shows with the popup dialog...
case 2: our add-in running before excel show up:
![image](https://user-images.githubusercontent.com/6204704/32361854-3a9a159a-c09f-11e7-89c6-cbab4dc66d78.png)

Thanks.

**Comment by szjfhb** [comment]
hi @jozefizso , any idea how to avoid excel splash screen show too long time?
Thanks.

**Comment by jozefizso** [comment]
You should contact MSDN Technical Support for issues related with how MS Excel works.

**Comment by szjfhb** [comment]
@jozefizso OK, thanks.  I will... But i just suppose I can find some help here too. 
Due to now I want do this kind of work with netoffice.

Thanks, Jozef.
