### ISSUE TITLE
How to publish the outlook add-in

### ISSUE THREAD

**Issue by qiruiaaa** [NetOfficeFw/NetOffice#200]
The outlook add-in has been developed, which is effective when debugging with visual studio 2013 . But how can i pack and distribute the dll files to other people?

**Comment by qiruiaaa** [comment]
Thank you very much, but I just started to learn outlook add-in development, trying to pack the project generated dll into an installation file, but it doesn't work, how does this dll file relate to outlook? Can you help provide detailed guidance?

**Comment by Linhin** [comment]
To let outlook recognize the dll file of your addin, you have to register it. Then you need to let Outlook load it when Outlook start. To do these things, you can create a setup project in visual studio and:
-Add your dll and independences into setup project and set vsdrpCOM to register it. Your Addin class with ProgId will be registered in the user computer.
-Then add a register key in setup project to set Outlook load you Addin (Outlook-Addin-You add in ProgId).

Or you can use COM Shim wizard in this instruction (https://msdn.microsoft.com/en-us/library/bb508939(v=office.12).aspx) and they will do all those thing for you.

**Comment by qiruiaaa** [comment]
i have already solved this problem，by regasm.exe，thank you
