### ISSUE TITLE
workbook.Add() vs workbook.Sheets.Add(Nothing, worksheet)

### ISSUE THREAD

**Issue by matteshe** [NetOfficeFw/NetOffice#201]
Hi,

I found a difference between Excel 2010 and Excel 2016.

The function workbook.Add() works differently. In 2010 it add a new worksheet to the end. In 2016 it add a new sheet in front.

For a workbook with only one sheet I needed to use the Function Add(Nothing, worksheet) in order to add the new one as second.

Is this a bug or a feature?

best regards,

Mattes

**Comment by jozefizso** [comment]
That's behavior of MS Excel 2010 and 2016.
