### ISSUE TITLE
Start Excel Application Modal

### ISSUE THREAD

**Issue by matteshe** [NetOfficeFw/NetOffice#204]
Hi,

is there a way to start the excel application as modal "Dialog". I start excel out of an application. The bad thing is, that the user can still use the application while excel is open. This lead to access violations. It would be nice, if one could block the appliation as long as excel is open.

**Comment by jozefizso** [comment]
Excel is an independent process so it cannot work in a modal way.

You can check if the Excel process is running.

**Comment by matteshe** [comment]
The problem is, one can't check, because I'm a plugin in an other application. So if you do something in the other app it doesn't care about my plugin and an open excel process.

Anyway, it looks like I found a solution.
1) create new form with modal dialog
2) open excel (the underlying app is blocked from the dialog)
3) handle open and close events in order to unblock the underlying form
