### ISSUE TITLE
How is add-ins signed by Trusted Publisher

### ISSUE THREAD

**Issue by maliutin** [NetOfficeFw/NetOffice#205]
The add-in is created for .NET 4.6.1.

What should I do that the add-in works with the security option without the warning message?

The options:
![image](https://user-images.githubusercontent.com/10669340/39990704-efc2c24c-5775-11e8-9243-5ef751ff3992.png)

**Comment by jozefizso** [comment]
The supported way of using add-ins in this scenario is to create a native COM Shim wrapper for the .NET Add-in.

Normally, you will get this warning as the add-in DLL file is not digitally signed:

![addin-unsigned](https://user-images.githubusercontent.com/287778/39991917-604e8a0a-5771-11e8-9ed0-caa609b5cb09.png)

You can sign the DLL using your Authenticode Certificate and the [signtool.exe](https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe)

The signed add-ins will be disabled by default, but user can select to trust the code signed by the actual certificate:

![screenshot_051418_121829_pm](https://user-images.githubusercontent.com/287778/39991992-9f82d4d8-5771-11e8-941f-38a6cb9a9a66.jpg)

![untitled_clipping_051418_121937_pm](https://user-images.githubusercontent.com/287778/39992004-a504b4a8-5771-11e8-8aaf-75bd875967ab.jpg)


In enterprise scenarios, the administrator can manage the list of trusted publishers, you will find more details in article [Plan Trusted Publishers settings for Office 2010
](https://docs.microsoft.com/en-us/previous-versions/office/office-2010/ff428091(v=office.14)) and the Office Support article [Add, remove, or view a trusted publisher](https://support.office.com/en-us/article/add-remove-or-view-a-trusted-publisher-87b3d5a3-b68c-4023-87c4-7cc78a44d7ed)

This way, the enterprise users will have add-ins enabled by default.

**Comment by maliutin** [comment]
Hi @jozefizso 

Thanks for your answer.

I did all steps which you wrote. But I cannot get the result in the 3rd picture. Excel does not see my signature.

Can you tell:
1. What version of SDK did you use?
2. Can you write an example of sign command?
3. Did you sign all dlls only one?

**Comment by maliutin** [comment]
Hi @jozefizso 

Thanks for the comment.

I created the COM shims and signed them.

**Comment by maliutin** [comment]
[Here](https://github.com/maliutin/ComAddinShim) are my examples of COM Shims for Excel and Word.

**Comment by jozefizso** [comment]
Those shims looks good.
