### ISSUE TITLE
Unable to create TaskPane that is located in seperate project

### ISSUE THREAD

**Issue by simpert** [NetOfficeFw/NetOffice#206]
Creating `TaskPane` via the handle `Addin` CustomPane attribute will work to create task pane as long as the pane is in the same assembly. I have my winforms usercontrols located in a separate com visible assembly. When I reference a usercontrol from outside assembly with attribute the `CustomTaskPane` Info object is created however the pane never shows up. Further, the `TaskPaneInfo` object has its Pane property set to null.

I would love to not use the attribute to create panes at all as my project requires a few seperate panes. I have tried to create TaskPanes in many different ways to no avail. Testing every solution with both a user control from within `Addin` assembly as well my control assembly.

I tried using the CtpFactory code from the examples to no avail. A Exception is always thrown.

I also tried the VSTO way of creating panes.
simply using CustomTaskPanes.Add(pane, name).

This way The TaskPaneInfo is returned and upon setting propertied including visible to true the pane never shows.

Maybe I am using the library wrong.
some code I have tried:
``` csharp
                var assName = typeof(TUserControl).Assembly.GetName().Name;
                var tName = typeof(TUserControl).Name;
                var taskPane = TaskPaneFactory.CreateCTP($"{assName}.{tName}", taskPaneName, Type.Missing);

                taskPane.DockPosition = MsoCTPDockPosition.msoCTPDockPositionRight;
                taskPane.Width = 500;
                taskPane.Visible = true;
``` 

exception is always thrown
ex. message: **Failed to proceed Method on Office.ICTPFactory=>CreateCTP.**
inner ex. message **Unable to create specified ActiveX control.**

and
``` csharp
//var uc = new MainPaneUserControl();
var taskPane = TaskPanes.Add( typeof(MainPaneUserControl), taskPaneName);
taskPane.DockPosition = MsoCTPDockPosition.msoCTPDockPositionRight;
taskPane.Width = 500;
taskPane.Visible = true;
``` 
the Pane property on resulting TaskPaneInfo is always null.

**Comment by Linhin** [comment]
Did you try to register for the assembly of Custom Taskpane. I should be set com visible and also need to be register to allow it will be recognized.

**Comment by jozefizso** [comment]
You must register your Task Pane as COM object under the name `$"{assName}.{tName}"`
