### ISSUE TITLE
How To Use UI  In Different OFFICE Version？？？

### ISSUE THREAD

**Issue by tan133** [NetOfficeFw/NetOffice#208]
can I Only use Ribbon when the Office's version is 2007 or later
 and
Only use CommanrdBar when  the Office's version is 2003 or behavior
 and 
Only use modernUI  when the Office's version is 2019 or later(i heared that 2019's UI has changed a lot)

**Comment by jozefizso** [comment]
Yes, you can implement CommandBar and Ribbon in a single NetOffice add-in.
