### ISSUE TITLE
Parse custom parameter to Word-AddIn by starting a Word-Instance

### ISSUE THREAD

**Issue by tmpSH** [NetOfficeFw/NetOffice#209]
Hi

I have used NetOffice.OfficeApi for development a custom Word-Addin, that is integrated inside the ribbon of word. I now need to parse during the start of a word instance a parameter to this Add-In.
Is this possible and if, how?

The background is, that I want to start different word instances and each parse another custom parameter to my Word-AddIn, so that my Word-AddIn can react on it.

One idea from me, was e.g. to create a link to Word and rename the link (put the parameter into the link name) or put the parameter inside the link comment, but I was not able to access this information from my WordAddin.

With best regards
Stefan

**Comment by maliutin** [comment]
> I now need to parse during the start of a word instance a parameter to this Add-In.

Do you mean the reading of parameters during the start of you Add-In?

> to create a link to Word

Do you mean a command line which is used in a shortcut?

If yes, you can get the command line during the start of your add-in. For that, you can use [Environment.CommandLine](https://msdn.microsoft.com/en-us/library/system.environment.commandline%28v=vs.110%29.aspx) or [Environment.GetCommandLineArgs](https://msdn.microsoft.com/ru-ru/library/system.environment.getcommandlineargs(v=vs.110).aspx)

**Comment by tmpSH** [comment]
Hi,

yes this was my idea. But then I can unfortunatety only use the specified word parameters like:
"C:\Programme\Microsoft Office\Office\Winword.exe" /a
"C:\Programme\Microsoft Office\Office\Winword.exe" c:\Dateiname1.doc c:\Dateiname2.doc 

I want to start WORD e,g so:
"C:\Programme\Microsoft Office\Office\Winword.exe" ident="PROD"
"C:\Programme\Microsoft Office\Office\Winword.exe" ident="TEST"
and react in my WordAddin to my custom parameter ident which is of type string with possible values PROD, TEST, …. I need the information in my WordAddIn that is should be startet in "PROD" or "TEST" or … and must parse somehow this information to my AddIn.

I have found no Word Parameter where I can parse such a custom text string to my WordAddIn.

**Comment by maliutin** [comment]
I suppose you should use:

`"C:\Programme\Microsoft Office\Office\Winword.exe" /ident="PROD"`

because an argument name must start from `/` symbol, otherwise Word tries to implement it as file name.

**Comment by tmpSH** [comment]
Hi,

thanks. This seems to work.
