### ISSUE TITLE
Excel auto clear Undo stack problem

### ISSUE THREAD

**Issue by Linhin** [NetOfficeFw/NetOffice#21]
Hi, I'm new with NetOffice. I'm using VSTO to create an Excel Addin in Office 2007 and later. However with VSTO, undo stack is cleared when I use the add-in's function to modify content of worksheets. I need to keep undo stack remain for user's convenience however it is impossible with VSTO. 
So I want to migrate to NetOffice, but could NetOffice Add-in keep undo stack remain?

**Comment by jozefizso** [comment]
NetOffice is only wrapper for Excel COM API and so is VSTO. In general, if this is an Excel behavior, you will get the same results in VSTO and NetOffice.

**Comment by Linhin** [comment]
Ok, Thank you jozefizso!
