### ISSUE TITLE
Receiving System.UnauthorizedAccessException when running NetOffice on machine without office

### ISSUE THREAD

**Issue by alexdefine** [NetOfficeFw/NetOffice#210]
Trying to run app that use NetOffice on server which doesn't have office.

> Receiving this exception:
> System.UnauthorizedAccessException : Retrieving the COM class factory for component with CLSID {00024500-0000-0000-C000-000000000046} failed due to the following error: 80070005 Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)).

Any ideas what my might cause the problem or how to fix it? 
Thank you

**Comment by maliutin** [comment]
NetOffice is interop for COM library of MS Office.

You cannot use it without the instance of MS Office.

**Comment by alexdefine** [comment]
Thank you for response.
@maliutin is there any way to avoid installing entire MS Office?

**Comment by maliutin** [comment]
The Microsoft documents are OpenXML format.

To generate docx or xlsx files I usually use only XML and ZIP libraries.

**Comment by alexdefine** [comment]
@maliutin Thanks a lot!
