### ISSUE TITLE
Documentation enhancements

### ISSUE THREAD

**Issue by clawfrank** [NetOfficeFw/NetOffice#212]
I was just reading through the [performance page](https://netoffice.io/documentation/technical/performance.html) and noticed you didn't have VSTO listed. It seems like its inclusion would be helpful (it has been for me!). I have sample code I wouldn't mind contributing, and updating that page to include, but the HTML is stored in a zip file... is that meant to be updated?

By the way, this entire project is very impressive, the amount of work that's put into this is really extensive and it shows.

**Comment by jozefizso** [comment]
The documentation for performance is few years old - before even VSTO was created by Microsoft.

Source code for the documentation is here: https://github.com/NetOfficeFw/Docs

PS: Credits go to [Sebastian Lange](https://github.com/SebastianDotNet) who developed all the NetOffice code. His primary repository is here: https://osdn.net/projects/netoffice/
