### ISSUE TITLE
How correctly subscribe and unsubscribe to events in Excel add-in for PowerPoint?

### ISSUE THREAD

**Issue by maliutin** [NetOfficeFw/NetOffice#215]
Hi folk

I need to implement the following scenario:
1. Create Excel Add-In.
2. Insert Excel table into a PowerPoint silde (There's MS Office 2010 x64).

Bellow is the exaggerated example:
```c#
using System;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using NetOffice;
using NetOffice.Tools;
using NetOffice.ExcelApi.Tools;

namespace ClassLibrary1
{
    [ComVisible(true)]
    [COMAddin("PP001 example", "PP001 example", LoadBehavior.LoadAtStartup)]
    [ProgId("ExcelAddin.PP001Example"), Guid("C79A9335-C001-4A66-8282-E93CEFBC7863"), Codebase, Timestamp]
    public class Addin : COMAddin
    {
        public Addin()
        {
            OnConnection += Addin_OnConnection;
            OnStartupComplete += Addin_OnStartupComplete;
            OnBeginShutdown += Addin_OnBeginShutdown;
            OnDisconnection += Addin_OnDisconnection;
        }
        private void Addin_OnConnection(object application, ext_ConnectMode connectMode, object addInInst, ref Array custom)
        {
            MessageBox.Show("Addin_OnConnection");
            System.Diagnostics.Debug.Print("Addin_OnConnection");
        }
        private void Addin_OnStartupComplete(ref Array custom)
        {
            // this.Application.WorkbookActivateEvent += Application_WorkbookActivateEvent;
            System.Diagnostics.Debug.Print("Addin_OnStartupComplete");
        }
        private void Addin_OnBeginShutdown(ref Array custom)
        {
            System.Diagnostics.Debug.Print("Addin_OnBeginShutdown");
        }
        private void Addin_OnDisconnection(ext_DisconnectMode removeMode, ref Array custom)
        {
            System.Diagnostics.Debug.Print("Addin_OnDisconnection");
        }
        private void Application_WorkbookActivateEvent(NetOffice.ExcelApi.Workbook wb)
        {
            System.Diagnostics.Debug.Print("Application_WorkbookActivateEvent");
        }
    }
}
```
This code works correct. I.e. we pass the following steps:
1. Create a new Presentation.
2. Insert an Excel table into the slide. In this point the EXCEL process has been started.
3. Create new slide. In this point the EXCEL process has been closed.
4. Open the first slide and start editing the Excel table. In this point the EXCEL process has been started.

![2018-08-24-12-35-59](https://user-images.githubusercontent.com/10669340/44578021-3376e700-a79b-11e8-8ebc-0c285e0bfe1a.gif)

Next, I try to insert the code `this.Application.WorkbookActivateEvent += Application_WorkbookActivateEvent;`
```c#
private void Addin_OnStartupComplete(ref Array custom)
{
    this.Application.WorkbookActivateEvent += Application_WorkbookActivateEvent;
    System.Diagnostics.Debug.Print("Addin_OnStartupComplete");
}
```

And catch the issue: 
In the step 3 the EXCEL process is not clossed and when I try to edit the Excel table in the step 4, I see error message:
![image](https://user-images.githubusercontent.com/10669340/44577309-6b7d2a80-a799-11e8-83c6-205dd2237907.png)

![2018-08-24-12-36-53](https://user-images.githubusercontent.com/10669340/44578044-425d9980-a79b-11e8-8b7d-b801921b1c27.gif)

Maybe I'm doing something wrong?

How should I implement subscription and unsubscription to WorkbookActivateEvent and WorkbookDeactivateEvent events?

**Comment by maliutin** [comment]
Hi @jozefizso 

Do you have any idias?

**Comment by jozefizso** [comment]
This may be relevant to this scenario:

> **Excel OLE Embedding Errors if you have Managed Add-In Sinking Application Events in Excel**
>
> Managed addins/components that sink events on the Application object may cause problems with OLE functionality in that instance of Excel, resulting in errors or possible crash of host application trying to edit Excel embedded objects.  Managed addins can avoid this problem with custom code. Users seeing this problem can avoid the problems using an Excel instance that does not load the managed addin.
>
> https://blogs.msdn.microsoft.com/vsofficedeveloper/2008/04/11/excel-ole-embedding-errors-if-you-have-managed-add-in-sinking-application-events-in-excel/
