### ISSUE TITLE
I cannot get the onLoad callback from the RibbonUI (ribbon xml) to work in 1.7.4.3, this works in 1.7.3

### ISSUE THREAD

**Issue by samatrhea** [NetOfficeFw/NetOffice#217]
Hi,

I am a happy user of NetOffice and recently i decided to update from version 1.7.3 to 1.7.4.3. In our RibbonXml we are using the *onLoad* callback to set a `Office.IRibbonUI RibbonUi` property on the Addin class. This is done so we can call `InValidate()` on it.

When i updated to 1.7.4.3 the method, for which the name I set in the onLoad xml tag of the customUI xml element, is no longer called. I tried to reproduce this on the RibbonUi example in the IExtensibility COMAddin folder. I added the onLoad xml tag and corresponding method in the Addin class and there i have the same problem.

In the ribbon XML if have the following

```
<customUI xmlns="http://schemas.microsoft.com/office/2006/01/customui" onLoad="OnLoadRibbonUi" >"
```

This is the corresponding method in the Addin class:

``` 
internal Office.IRibbonUI RibbonUi { get; set; }

public void OnLoadRibbonUi(Office.IRibbonUI ribbonUi)
        {
            this.RibbonUi = ribbonUi;
        }
```

Any help would be appreciated.

**Comment by maliutin** [comment]
It is working in my side.
How do you load the xml file with customUI elements? And what applications do you use in tests?

**Comment by samatrhea** [comment]
Hi,

Thanks for having a look at this. Regarding your questoin:

I am not loading an xml, it is constructed based on specific conditions (application plugins loaded or not, permissions, etc). 

Below you can see a partial class, i realize this is a bit limited. What i will do shortly is take the example that i mentioned earlier and add an onLoad callback in the xml like i did earlier where i noticed that for the example it wasn't working either

```

public class Addin : IDTExtensibility2, NetOffice.OfficeApi.Native.IRibbonExtensibility, NetOffice.OfficeApi.Native.ICustomTaskPaneConsumer

public NetOffice.OfficeApi.Native.IRibbonUI RibbonUi { get; set; }

public string GetCustomUI(string ribbonID)
        {

            ribbonXml = <some magic here that constructs a valid ribbon xml string>
            return ribbonXml;
        }

        public void OnLoadRibbonUi(NetOffice.OfficeApi.Native.IRibbonUI ribbonUi)
        {
            this.RibbonUi = ribbonUi;
        }

```

**Comment by samatrhea** [comment]
Hi,

While i was constructing a sample app without the nitty gritty of our own application i noticed that in the ComAddin class now provides a built in property `RibbonUI` (notice that in my code i put it in myself and called in RibbinUi, lower case i at the end).

When using the build-in property and renaming the `onLoad` tag in the ribbon-xml to `CustomUI_OnLoad` it all worked again. 

this issue can be closed, but can you confirm that it's no longer the intention to allow users to define their own name for the "onLoad" call-back method when using the `ComAddin` class?

**Comment by samatrhea** [comment]
That is what we are doing. thanks for the feedback and if you are interested in seeing what we are doing with NetOffice have a look here https://github.com/RHEAGROUP/CDP4-IME-Community-Edition
