### ISSUE TITLE
Support for .NET Core 3

### ISSUE THREAD

**Issue by tb-mtg** [NetOfficeFw/NetOffice#219]
Could you please add support for .Net Standard 2.0 / .Net Core 2.1 ?

**Comment by jozefizso** [comment]
NetOffice runs exclusively under .NET Framework as it is a library which wraps the COM interfaces.

When .NET Core 3 will support the COM technology, it would make sense to switch to the .NET Standard.

**Comment by jozefizso** [comment]
.NET Portability Report

http://htmlpreview.github.io/?https://gist.githubusercontent.com/jozefizso/51fce7993434ab200e8fcec33dacb9b2/raw/d1c766093cd920f835454c984fe1a1cc8b2a2017/NetOfficePortabilityAnalysis.html

**Comment by jozefizso** [comment]
Closing the issue for now.

We will reevaluate this when .NET Core 3.0 is released.

**Comment by AndreyRavkov** [comment]
Hello,
looks like .net core 3.0 is released.

**Comment by jozefizso** [comment]
I tried MS Office app automation using .NET Core 3 application. I could use existing NetOffice assemblies in .NET Core 3 project and it could call Office APIs well.

I tried it on MS Word samples from the NetOffice 1.7.4 code.

I'm not sure how addins works under .NET Core.

**Comment by jozefizso** [comment]
The add-in targeting .NET Core 3 and using NetOffice should be possible.

.NET Core 3 supports COM+, exposing components from Core assemblies and it can generate the native COM hosting library.

There are some pain points right now - addin must target either 32-bit or 64-bit platform, universal code does not work (this is limitation of the generated hosting library).

Using this document

**Comment by tb-mtg** [comment]
So is a new release coming that will support for .Net Standard 2.0?

**Comment by AzizFacilex** [comment]
@jozefizso  could you please share an example of the add-in on .NET Core 3 ?

**Comment by emad981** [comment]
@jozefizso We are still waiting for .Net Core 3.1 compatibility. Thanks in advance

**Comment by jozefizso** [comment]
@emad981 you are welcome to make pull request with related implementation.

**Comment by norvegec** [comment]
My setup: both .Net Framework 4.7.2 and .Net Core (SDK 2.1, 2.2, 3.1) installed.
dotnet new console ExcelDemo && cd ExcelDemo

```csharp
using var xlApp = new Application();
var wb = xlApp.Workbooks.Open(filePath);
object oSheet = wb.Sheets["Sheet1"]; // throws 
```
Stack trace:
```logs
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.ComponentModel.TypeDescriptor.ComNativeDescriptorProxy..ctor()


   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at System.ComponentModel.TypeDescriptor.CheckDefaultProvider(Type type)
   at System.ComponentModel.TypeDescriptor.NodeFor(Type type, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.NodeFor(Object instance, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)
   at NetOffice.CoreFactoryExtensions.GetFactoryInfo(Core value, Dictionary`2 hostCache, ICOMObject caller, Object comProxy, Boolean wantTheDuck, Boolean throwException)
   at NetOffice.Core.GetInstanceFactoryInfo(ICOMObject caller, Object comProxy, Boolean throwException)
   at NetOffice.Core.CreateObjectFromComProxy(ICOMObject caller, Object comProxy, Boolean allowDynamicObject)
   at NetOffice.CorePropertyGetExtensions.ExecuteReferencePropertyGetInternal(Core value, ICOMObject caller, String name, Object[] validatedArgs)
   at NetOffice.CorePropertyGetExtensions.ExecuteReferencePropertyGet(Core value, ICOMObject caller, String name, Object argument)
   at NetOffice.ExcelApi.Sheets.get_Item(Object index)
```

**Comment by jozefizso** [comment]
@norvegec packages for NetOffice targeting .NET Core 3 are not published yet.

You can try using the code from the **dev/netoffice_v1.8** branch: https://github.com/NetOfficeFw/NetOffice/tree/dev/netoffice_v1.8

**Comment by norvegec** [comment]
Tried to build with build.cmd (the only difference, I've changed line 16 to `dotnet msbuild ...`. The output is the following:
``logs
C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\dev\Experiment\NetOffice-dev-netoffice_v1.8\Source\Office\OfficeApi.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\dev\Experiment\NetOffice-dev-netoffice_v1.8\Source\Office\OfficeApi.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\dev\Experiment\NetOffice-dev-netoffice_v1.8\Source\Office\OfficeApi.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Windows.Forms". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\dev\Experiment\NetOffice-dev-netoffice_v1.8\Source\NetOffice\NetOffice.csproj]
C:\Users\dbardakov\.nuget\packages\microsoft.build.tasks.git\1.0.0\build\Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory 'C:\dev\Experiment\NetOffice-dev-netoffice_v1.8\Source\NetOffice'. [C:\dev\Experiment\NetOffice-dev-netoffice_v1.8\Source\NetOffice\NetOffice.csproj]
C:\Users\dbardakov\.nuget\packages\microsoft.sourcelink.common\1.0.0\build\Microsoft.SourceLink.Common.targets(52,5): warning : Source control information is not available - the generated source link is empty. [C:\dev\Experiment\NetOffice-dev-netoffice_v1.8\Source\NetOffice\NetOffice.csproj]
Contribution\Controls\InstanceMonitor.cs(5,22): error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?) [C:\dev\Experiment\NetOffice-dev-netoffice_v1.8\Source\NetOffice\NetOffice.csproj]
...
``
I have 2 questions:
- I suppose most of projects should be retargeted to `netstandard2.0` before the build?
- there is a dedicated branch for .NetCore 3. What are your plans about it?

**Comment by jozefizso** [comment]
NetOffice will not support **netstandard2.0** as it requires data types from **netcoreapp3.1** SDK.

NetOffice will still support previous .NET Frameworks, so to build it, you need SDKs for .NET 4.0, 4.5 and 4.7 for now.

**Comment by mbostwick** [comment]
@jozefizso are you going to post the dotnet core version to nuget  ?

**Comment by jozefizso** [comment]
@mbostwick current packaging scripts for NetOffice are not yet compatible with .NET Core so I will not release native .NET Core packages anytime soon.

With .NET Core 3.1 and 5 you can reference current NetOffice packages and they will work when using Windows/WinForms targets.

**Comment by SID9-HoneyBee** [comment]
I am developing in a .Net5 Wpf environment. can i use it?

**Comment by jozefizso** [comment]
@SID9-HoneyBee when target the Windows platform, you can use the existing NetOfficeFw packages even with .NET 5 projects.

**Comment by budul100** [comment]
@jozefizso When I build my Excel add-in with _<TargetFramework>net5.0-windows</TargetFramework>_ and try to register it with regasm, then I am receiving the following error:

`
error RA0000 : Could not load file or assembly "System.Runtime.InteropServices, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or one of its dependencies. The system cannot find the file specified. 
`

Do you have an idea what could possibly be wrong?

**Comment by budul100** [comment]
> 
> 
> @jozefizso When I build my Excel add-in with `<TargetFramework>net5.0-windows</TargetFramework>` and try to register it with regasm, then I am receiving the following error:
> 
> `error RA0000 : Could not load file or assembly "System.Runtime.InteropServices, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or one of its dependencies. The system cannot find the file specified. `
> 
> Do you have an idea what could possibly be wrong?

I have found out now that the registry must be done by using `regsvr32` and the `*.comhost.dll`, e.g.:

> regsvr32 ExampleAddin.comhost.dll

But now I wonder whether the function marked with `[ComRegisterFunctionAttribute]` are still called?

**Comment by jozefizso** [comment]
@budul100 Please, read the documentation about registering COM Classes in .NET 5. The toolchain changed.

**Comment by jozefizso** [comment]
Closing in favor of #343
