### ISSUE TITLE
Chart/Word ChartData.BreakLink supports only 14, 15, 16 office

### ISSUE THREAD

**Issue by maliutin** [NetOfficeFw/NetOffice#22]
Hello

The source code contains the information that `ChartData.BreakLink` methods are not supported by Word 2007 and PowerPoint 2007.

https://github.com/NetOfficeFw/NetOffice/blob/9a9f7fcecfa71f5bbfd8dfbc0b781df52d00f199/Source/Word/DispatchInterfaces/ChartData.cs#L148-L149

https://github.com/NetOfficeFw/NetOffice/blob/9a9f7fcecfa71f5bbfd8dfbc0b781df52d00f199/Source/Word/DispatchInterfaces/ChartData.cs#L148-L149

Is there any reason?

Now I am trying to implement mine code with these methods. And my tests pass know.

Thank you in advance.

P.S. Now I am working with v1.7.3.

**Comment by jozefizso** [comment]
Can you provide more information about your code and tests? Do you mean your code compiles and runs in MS Office 2007? If yes, does the `BreakLink` method work as expected and the same as on newer MS Office or it just silently executes and does not do anything?

**Comment by maliutin** [comment]
Hi

I have a task:

1. Load a xlsx file from a server. The file must have one chart on the first sheet.
2. The chart should be copied to an opened word document in the selected place.

After that, we need to clear the source formula because it contains the link to the loaded excel file. For that `BreakLink` is used:

```c#
private void InsertChart(Word.ContentControl contentControl, Excel.Shape sourceShape)
{
    sourceShape.Copy();

    using (var controlRange = contentControl.Range)
    {
        controlRange.Paste();
    }

    System.Windows.Forms.Application.DoEvents();

    using (var controlRange = contentControl.Range)
    using (var shapeRange = controlRange.InlineShapes)
    using (var newShape = shapeRange[1])
    using (var newChart = newShape.Chart)
    using (var chartData = newChart.ChartData)
    {
        chartData.BreakLink();
    }
}
```

It also works for PowerPoint scenarios.

**Comment by jozefizso** [comment]
The `ChartData` dispatch interface does not exist in the Word 2007 interop library so the documentation is correct.

![image](https://user-images.githubusercontent.com/287778/47868543-b86a2680-de04-11e8-8036-9afb63f15487.png)

![image](https://user-images.githubusercontent.com/287778/47868481-8d7fd280-de04-11e8-9e3e-576988a51587.png)


There is an interface `IMsoChartData` in the Office 2007 interop library and it contains the `BreakLink()` method. That's may be why this functionality works in Office 2007.
