### ISSUE TITLE
when i use the IRTDUpdateEvent.UpdateNotify() it will occur error

### ISSUE THREAD

**Issue by 571821151** [NetOfficeFw/NetOffice#222]
i want to refrash data use rtd fuction ,but when i use this function, it will occur error Failed to proceed Method on Excel.Arc=>UpdateNotify.

**Comment by 571821151** [comment]
![image](https://user-images.githubusercontent.com/20980198/46727001-36c62380-ccb2-11e8-86b6-c9dc1f031623.png)

**Comment by 571821151** [comment]
i use this object as IRTDUpdateEvent

**Comment by jozefizso** [comment]
Hi,
unfortunately it is not clear what you are asking and what your issue is.

Can you describe in more details what is your scenario and what is not working?

**Comment by 571821151** [comment]
sorry ,my english is not so good to descripe my question very clearly. ![image](https://user-images.githubusercontent.com/20980198/46776287-830a7580-cd3d-11e8-99da-40cfef066191.png)
it is when i use   RealtimeDataServer to create a RTD function. i pass the callbackObject when ServerStart and i use the callbackObject.UpdateNotify() to let excel update value when my data is ready.it will crash with an exception 
![image](https://user-images.githubusercontent.com/20980198/46776473-4b4ffd80-cd3e-11e8-8993-c9ccd795b7af.png)
it seems a reflex error.
i want to know why and how to use callbackObject.UpdateNotify() correctly? can i use the native rtdserver in netoffice ,i need an example

**Comment by 571821151** [comment]
I have another question :how can I change the visibility of ribbon button..

**Comment by jozefizso** [comment]
The Excel RTD sample works for me: https://github.com/NetOfficeFw/NetOffice/tree/v1.7.4.3/Examples/Excel/C%23/NetOffice%20COMAddin%20Examples/05%20Rtd%20Server
