### ISSUE TITLE
OlRibbonType.cs wrong enum for Microsoft.Outlook.Mail.Compose

### ISSUE THREAD

**Issue by der-berni** [NetOfficeFw/NetOffice#223]
The Enum Member "Microsoft_OutlookMail_Compose" in NetOffice.OutlookApi.Tools.OlRibbonType should be "Microsoft_Outlook_Mail_Compose"

**Comment by jozefizso** [comment]
Hi, thanks for reporting this bug.

Yes, the `OlRibbonType.Microsoft_OutlookMail_Compose` is converted in the `OlCustomUIAttribute` to the Outlook Ribbon ID by replacing `_` with `.` so the ribbon ID for this is incorrect.

**Comment by jozefizso** [comment]
Fixed in NetOffice 1.7.4.4

**Comment by jozefizso** [comment]
Finally fixed in NetOffice 1.7.4.5
