### ISSUE TITLE
Access Excel cell via named range

### ISSUE THREAD

**Issue by matteshe** [NetOfficeFw/NetOffice#228]
According to the docs of Microsoft it should be possible to access a cell or range via a named range.

Range("namedRange")

If I do this with NetOffice I end in an PropertyCOMException: Failed to proceed PropertyGet on Workshhet.

Do you have any advice hoe how to access a cell with a defined name?

it works if you are on the sheet where the name is defined, but not if you are on a different sheet.

table1 namedRange
access namedRange in table 2 fails.

**Comment by jozefizso** [comment]
I tried this in the **Excel Example01** and it works as expected, the named range object is returned.

```csharp
// draw back color and call the BorderAround method
workSheet.Range("$B2:$B5").Name = "FirstRange";
workSheet.Range("$B2:$B5").Interior.Color = utils.Color.ToDouble(Color.DarkGreen);
workSheet.Range("$B2:$B5").BorderAround(XlLineStyle.xlContinuous, XlBorderWeight.xlMedium, XlColorIndex.xlColorIndexAutomatic);

var namedRange = workSheet.Range("FirstRange");
namedRange.Cells[1, 1].Value = "FirstRange";
```

**Comment by jozefizso** [comment]
If you don't have a named range defined, it may return null object or throw an exception. I'm not sure about exact behavior accross Excel versions.

**Comment by matteshe** [comment]
One more hint, there is a difference in excel to have a name reference on the whole book or only to a sheet. It looks like, that you can only address names for a sheet, but not for the whole workbook.

**Comment by jozefizso** [comment]
Yes, named ranges are local to the sheet.

The **NameA1** is not defined in the **Tabelle2** sheet.

**Comment by matteshe** [comment]
So how is the solution? Excel is able to define a scope on book or sheet. How can we do this in NetOffice? This is standard in excel since many years.

Am 6. November 2018 15:34:09 MEZ schrieb Jozef Izso <notifications@github.com>:

**Comment by SebastianDotNet** [comment]
Ich glaueb ich weiss warum.
I need your calling Code to clearify the issue because you may adressing the wrong instance for a special interop/netoffice syntax issue.

**Comment by jozefizso** [comment]
Closing, as named ranges can be access without the worksheet.
