### ISSUE TITLE
ShimLoader fails to be registered by regsvr32 due to error

### ISSUE THREAD

**Issue by tsuga** [NetOfficeFw/NetOffice#229]
I'm trying out `NetOfficeFw/NetOffice/NetOfficeShimLoader/ShimLoader/` with VS2017 on Windows 10, after I re-targeted the project `ShimLoader` from VS2010 to VS2017.

The build is successful, but when it is registered by regsvr32.exe, I encountered the line 49　`ShimDebugMessageBox(L"Unexpected Result", L"DllMain");` in `Main/DllMain.cpp`.

The log file `ShimLoader.dll.log` has lines below:
```
DllMain::Initialize::Enter(06-12-2018 12:39:30 AM)
ShimArguments::Load::Enter
ShimArguments::LoadFile::Enter
ShimArguments::LoadFile::MissingFile
ShimArguments::LoadFile::Error
ShimArguments::Load::FailExit
ShimArguments::Unload::Enter
ShimArguments::Unload::Exit
DllMain::Initialize::FailExit
DllMain::Cleanup::Enter
DllMain::Cleanup::Exit
```

Do you have any ideas to resolve this issue?

Kind regards,
tsuga

**Comment by jozefizso** [comment]
Hi,
the shim loader is in development and not ready for general use.

You must have the *Manifest.xml* configuration file correctly configured so the shim can load addins.
