### ISSUE TITLE
OUTLOOK

### ISSUE THREAD

**Issue by gilyoktan** [NetOfficeFw/NetOffice#232]
Hello
I want to use NETOFFICE with OUTLOOK
either outlook is close or open - the pgm fails in CreateByRunningInstance
What am I doing wrong? Has anyone encountered this issue (and hopefully solved it)?
Have a nice day - and nice "endoftheyear holiday"
Gil Yoktan

**Comment by jozefizso** [comment]
Hi, what do you mean by "pgm"?

Do you get any exceptions when working with Outlook API? If so, please, provide the error messages.

**Comment by jozefizso** [comment]
Closing the issue as there's no response from the opener.
