### ISSUE TITLE
Office 365 and progid not found problem

### ISSUE THREAD

**Issue by Wally1962** [NetOfficeFw/NetOffice#235]
I have a problem with a program that used NetofficeFw.Word and Office365.
This is the code 

using NetOffice;
using Office = NetOffice.OfficeApi;
using NetOffice.OfficeApi.Enums;
using Word = NetOffice.WordApi;

                Word.Application app = new Word.Application();
                app.DisplayAlerts = WdAlertLevel.wdAlertsNone;
                Word.Document Doc = app.Documents.Open(FileA);
                SearchAndReplacePrivacy(Doc);

and when try to create New Word.Application return "progid not found" error

How can fix it?

**Comment by jozefizso** [comment]
Office 365 will install and register the Office automation interfaces.

Sometimes it may be needed to reinstall the Office 365 to fix registration issues.

More information about COM activation errors can be found also in the Windows Event Viewer.

**Comment by Wally1962** [comment]
Thanks
