### ISSUE TITLE
Creating a custom spellchecker for MS Word

### ISSUE THREAD

**Issue by encrypt0r** [NetOfficeFw/NetOffice#239]
Thank you for this useful project, I have been working on a custom spellchecking algorithm that plays well for languages that depend a lot on infixes. I have been trying to integrate it into Word via a Word Add-In. These are the things that I would like to be able to do:

1. Mark undefined words with squiggly lines (or any other formatting that doesn't affect the actual formatting of the range).
2. Add the suggestions to the context menu (I have actually been able to do that)

An even better thing is for me to be able to extend the built-in spellchecker, I have also seen people mention CSAPI but I couldn't find anything useful online, is it deprecated?

Is there a way to add ranges to `Range.SpellingErrors` or implement a custom [Dictionary](https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.word.dictionary?view=word-pia) that uses a custom algorithm?

**Comment by jozefizso** [comment]
I don't know if Office spellchecker can be extended.

**Comment by encrypt0r** [comment]
@jozefizso unfortunately I have the same feeling :(
https://github.com/GrammarSoft/proofing-gasmso/wiki/This-is-not-CSAPI
