### ISSUE TITLE
Debugging/Run Configuration & Breakpoints

### ISSUE THREAD

**Issue by JD-Robbs** [NetOfficeFw/NetOffice#24]
Hello there,

This looks great and I'm just starting out to see if this is a good VSTO replacement for my needs.

I wonder if there is any documentation on debugging projects using NetOffice to be able to set breakpoints/debug while NetOffice Add-Ins are running?

Thanks!

**Comment by jozefizso** [comment]
Set your breakpoints, attach to running MS Office application process and you can debug.

No special prerequisites are required.

**Comment by JD-Robbs** [comment]
You're a superstar - thanks a lot! 

Now it's to hoping that Microsoft doesn't remove COM Interop when 2019 comes around - and beyond. 😄

**Comment by jozefizso** [comment]
AFAIK the COM Add-in will be still available in future MS Office versions, although no new API will be introduced. Removing the support would break too much enterprise applications.

**Comment by JD-Robbs** [comment]
Yes, it'd be a bit of a nightmare, I suppose. By new APIs, you mean that they'll simply freeze what features are there, but VSTO/NetOffice would (probably) continue to work based on the current API feature set, I imagine?

**Comment by jozefizso** [comment]
Yes, that's correct.
