### ISSUE TITLE
Support about new/incoming office versions

### ISSUE THREAD

**Issue by GiorgosTsal** [NetOfficeFw/NetOffice#240]
I would like to know how long does it take to create the new APIs when a new version comes out. For example, from what I see, you don't support office version 2019. When will you get support for this version? I want to switch from Microsoft Interop to NetOffice.
Thank you in advance.

**Comment by jozefizso** [comment]
Is there a particular API you are missing from NetOffice?

NetOffice supports Microsoft Office 2016 API and so far 2019 has the same API set, so you can use NetOffice with it as well.
