### ISSUE TITLE
how to delete a named range in excel 

### ISSUE THREAD

**Issue by hoangvn79** [NetOfficeFw/NetOffice#242]
Hi!
I want to delete the range named in excel but I don't know how to do it. I use C #

**Comment by jozefizso** [comment]
You can use the `NamedRange.Delete()` method.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.tools.excel.namedrange.delete?view=vsto-2017#Microsoft_Office_Tools_Excel_NamedRange_Delete
