### ISSUE TITLE
Outlook quitEvent doesn't trigger

### ISSUE THREAD

**Issue by Hisendur** [NetOfficeFw/NetOffice#244]
After updating NetOffice to 1.7.4.5 the Outlook QuitEvent does not trigger. The event is subscribed to via the following commands in the OnConnection event.

```
OutlookApplication = this.Application;
OutlookApplication.QuitEvent += QuitEvent;
```
When I close Outlook this event is not triggered. Is this known? Can this be fixed?

Thank you

**Comment by jozefizso** [comment]
This event is no longer called by the MS Outlook 2000 and newer.

**Comment by jozefizso** [comment]
This is expected behavior of MS Outlook.

**Comment by Hisendur** [comment]
But how can I react to the closing of Outlook, if not via this event?

**Comment by jozefizso** [comment]
> If an add-in uses these events to commit data (for example, to store user settings or to report usage to a Web server), those activities will no longer take place. Depending on the scenario, this may or may not have a visible impact to users. To remedy the situation, the add-in developer can modify the add-in to be compatible with the changes, or an IT administrator can use group policy to restore the original behavior for a specific add-in.
>
> https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2010/ee720183(v=office.14)
