### ISSUE TITLE
Exception opening visio file

### ISSUE THREAD

**Issue by jorgemrDev** [NetOfficeFw/NetOffice#247]
We are using the library to work with visio files, reading files from a path, and open to processs, but in some cases we have an exception :

Error while processing Drawing1.vsdx  data:System.Collections.ListDictionaryInternal ErrorCode:-2147467259 InnerException:System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: 
An exception occurred.

and we dont have more detailed info about the error

**Comment by jozefizso** [comment]
From this description it is impossible to say what can be the cause of the issue.

**Comment by jorgemrDev** [comment]
the exception is on this line   doc = visioApp.Documents.Open(workingFilePath);

**Comment by jozefizso** [comment]
**COMException** can occur anywhere at anytime. This depends on what MS Office is doing.

**Comment by jorgemrDev** [comment]
but we have the error just opening file without doing anything more at this point

**Comment by jorgemrDev** [comment]
we are using this on a windows service
