### ISSUE TITLE
Examples that illustrate handling events.

### ISSUE THREAD

**Issue by krptodr** [NetOfficeFw/NetOffice#248]
I wanted to request the ability to have examples that illustrate handling events using NetOffice.

**Comment by jozefizso** [comment]
Example projects are here: https://github.com/NetOfficeFw/NetOffice/tree/master/Examples

There are several examples for working with events in Excel or Outlook.

eg. https://github.com/NetOfficeFw/NetOffice/blob/master/Examples/Excel/C%23/Standard%20Examples/ExcelExamples/Examples/Example08.cs
