### ISSUE TITLE
The issue about pack project

### ISSUE THREAD

**Issue by ZENBruce** [NetOfficeFw/NetOffice#253]
I finish my project use NetOffice and I want other people to use my Addin,but I don't know how to do.How to write into the regedit ?Do you have the guide about install and deploy?Thank you!!!

**Comment by jozefizso** [comment]
Use can use the **RegAddin** tool to register your addin.

**Comment by ZENBruce** [comment]
This issue has been solved,but I have another one.My addin can work on Outlook2007 and 2010,but cant't work on Outlook2013.And I use your examaple for Outlook,It aslo didn't work.The regedit LoadBehavior is 2.

**Comment by jozefizso** [comment]
You should refer to official Microsoft documentation for deploying addins to MS Outlook 2013.
