### ISSUE TITLE
Implement Application.SaveAsText and Application.LoadFromText in Access

### ISSUE THREAD

**Issue by vmsp** [NetOfficeFw/NetOffice#254]
These methods are undocumented but well known [1].

[1] https://blogs.msdn.microsoft.com/thirdoffive/2006/08/31/templates-quick-overview-of-saveastext-and-loadfromtext-aka-lets-get-boring-again/

**Comment by jozefizso** [comment]
Both methods are available in latest NetOffice v1.7.4.6:

`LoadFromText`: https://github.com/NetOfficeFw/NetOffice/blob/releases/netoffice_v1.7.4.6/Source/Access/DispatchInterfaces/_Application.cs#L3107
`SaveAsText`: https://github.com/NetOfficeFw/NetOffice/blob/releases/netoffice_v1.7.4.6/Source/Access/DispatchInterfaces/_Application.cs#L3094

**Comment by jozefizso** [comment]
Closing as this is already implemented.

**Comment by vmsp** [comment]
Thank you, Jozef!
