### ISSUE TITLE
Excel Worksheet.Copy does not work properly

### ISSUE THREAD

**Issue by MarcoBorn** [NetOfficeFw/NetOffice#255]
I get the following error message:
```
Failed to proceed Method on Excel.Worksheet=>Copy.
   bei NetOffice.Invoker.Method(ICOMObject comObject, String name, Object[] paramsArray)
   bei NetOffice.CoreMethodExtensions.ExecuteMethod(Core value, ICOMObject caller, String name, Object argument)

```
when I try to us the following command:
```
With ObjAppXL
  .Workbooks(StrQuellDatei).Sheets("Hinweise").Copy(before:= 
  .Workbooks(StrZielDatei).Sheets(1))
End With

```
The variables ObjAppXL, StrQuellDatei and StrQuellDatei were set before and accessing them also made no errors.

**Comment by jozefizso** [comment]
Please, provide more information about your issue.

The `Worksheet.Copy` works in latest NetOffice library when used as in you example.

**Comment by jozefizso** [comment]
Closing as there is no more information from issue opener.
