### ISSUE TITLE
Integrate MehApps.Metro with Taskpane of NetOffice

### ISSUE THREAD

**Issue by Linhin** [NetOfficeFw/NetOffice#258]
Helllo, I tried to integrate MehApps.Metro with TaskPane of NetOffice but it did not work. WPF UserControl is wrapped in NetOffice taskpane by ElementHost. However, when change wpf UserControl to Controls:MetroWindow, it does not works. Did anyone know how to intergrate MehApps.Metro with NetOffice TaskPane?

**Comment by jozefizso** [comment]
In general, you should be able to use any .NET library with you project.

May be the better place to get answer how to integrate MahApps.Metro is on https://stackoverflow.com/
