### ISSUE TITLE
System.ArgumentException when calling Application.GetActiveInstance()

### ISSUE THREAD

**Issue by DominikPalo** [NetOfficeFw/NetOffice#261]
I'm using the `GetActiveInstance()` method to connect my WPF to the running PowerPoint instance (more specifically the app is calling this method periodically every 1000ms to monitor when PowerPont starts/exits). Most of the time it works as expected, but sometimes this method fails with `System.ArgumentException` error. Here is the stack trace:

```
System.ArgumentException
  HResult=0x80070057
  Message=component
  Source=System
  StackTrace:
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)
   at NetOffice.RunningObjectTable.GetActiveProxyFromROT(String componentName, String className, Boolean throwOnError)
   at NetOffice.PowerPointApi.Application.GetActiveInstance()
```

I'm using the latest version from NuGet (1.7.4.4)

**Comment by jozefizso** [comment]
Which NetOffice nuget packages are you using?

This looks similar to the https://github.com/NetOfficeFw/NetOffice/issues/91 - which was present in the 1.7.3 source code.

If you use the **NetOffice** packages (without the **Fw** at the end), you are using a "rogue" version of NetOffice packages. Basically inside the package is still 1.7.3 release of NetOffice.

To get the real **1.7.4.4** release, please use **NetOfficeFw.PowerPoint**: https://www.nuget.org/packages/NetOfficeFw.PowerPoint

**Comment by DominikPalo** [comment]
@jozefizso thank you, I was not aware of that and we were using **NetOffice.PowerPoint** package... so, I've just switched to the **NetOfficeFw.PowerPoint** and the `ActivePowerPointApp.SlideShowBeginEvent` event is not fired anymore (the issue we have discussed today)

**Comment by DominikPalo** [comment]
I've just opened another issue for the problem mentioned in my last comment (https://github.com/NetOfficeFw/NetOffice/issues/262).
