### ISSUE TITLE
Add powerquery to the workbook object model

### ISSUE THREAD

**Issue by sylvainpiron** [NetOfficeFw/NetOffice#269]
Hi, 
Is it possible to add **powerquery** to the object model?
You can access it with interop by using late binding like this:
```
dynamic wb = app.ActiveWorkbook;
int cnt = wb.queries.Count;
System.Diagnostic.Debug.Print(cnt.ToString());
```
Thanks,
Best regards
Sylvain PIRON

**Comment by jozefizso** [comment]
Thanks for noticing there is a new API in Excel 2016 for this feature.

I don't ETA when this could be implemented, it mostly depends on how large is this new API surface.

**Comment by jozefizso** [comment]
Released in https://github.com/NetOfficeFw/NetOffice/releases/tag/v1.9.4
