### ISSUE TITLE
CoClassEventReflector.HasEventRecipients always return false

### ISSUE THREAD

**Issue by norvegec** [NetOfficeFw/NetOffice#277]
https://github.com/NetOfficeFw/NetOffice/blob/5f161cab885aa6223eead0f599f7b439597b5113/Source/NetOffice/Events/CoClassEventReflector.cs#L29

I suppose once conditions are met, should return true.

**Comment by jozefizso** [comment]
That's a great catch! 🙊

**Comment by jozefizso** [comment]
This won't be a straight forward fix. It looks like `CoClassEventReflector` class has much more bugs in its implementation.

**Comment by jozefizso** [comment]
Hi @norvegec,
this was fixed in v1.7.5 release
