### ISSUE TITLE
Is it possible to support UWP?

### ISSUE THREAD

**Issue by zzpbuaa** [NetOfficeFw/NetOffice#286]
Hi, I know this is more a question than an issue. But I didn't know where to post a question and I see somebody in other repo ask question in issues. So I post question here. Sorry for the inconvenience.
My question is just like the title: is it possible this library support UWP someday? When I tried to add in to project by Nuget, it says:

![image](https://user-images.githubusercontent.com/12425434/89988496-33d35a00-dcb2-11ea-947a-392163c08223.png)

**Comment by jozefizso** [comment]
Hi @zzpbuaa,
the **NetOffice.Core** package you are using is incorrect one. See issues #276 or #278
To use the correct NetOffice libraries, please user the **NetOfficeFw.Core** package and packages from https://www.nuget.org/profiles/netoffice


**Support for UWP**

I don't think we can support UWP (the `uap10.0` target) as it (AFAIK) does not have support for the required COM+ API.

**Comment by zzpbuaa** [comment]
@jozefizso , whoo. Suprised to know it's a fake lib. Thanks for all the information.

**Comment by jozefizso** [comment]
@zzpbuaa I noticed this sample which shows how to call MS Office API from UWP applications: https://stefanwick.com/2017/05/26/uwp-calling-office-interop-apis/
