### ISSUE TITLE
How about support of Office 2019/365

### ISSUE THREAD

**Issue by nxheinz** [NetOfficeFw/NetOffice#287]
Hi, 

Do you have any idea, if or when you will support Office 2019/365 ?

Thanks
Heinz

**Comment by jozefizso** [comment]
Are there any APIs you are missing from latest Office releases?

MS Office 2019 has the same API as 2016. O365 does not have notable changes.

NetOffice works well with both editions of Office.

**Comment by nxheinz** [comment]
Thanks for your quick replay.

I noticed that our wpf app using Office 2019/365 with Netoffice is running less stable than on older Office Versions.

Heinz

**Comment by jozefizso** [comment]
Which NetOffice version / nuget packages are you using?

And what's your scenario? Are you automating Office from the WPF app? Or is it running as an addin in Office apps?

**Comment by jozefizso** [comment]
When you automate MS Office applications, you must expect exceptions like this to occur and handle them gracefully.

**Comment by glautrou** [comment]
@nxheinz Did you solve your problem ?
