### ISSUE TITLE
Loading Application without addins

### ISSUE THREAD

**Issue by callidex** [NetOfficeFw/NetOffice#288]
Word etc support command line /a  to prevent add ins loading

https://support.microsoft.com/en-us/office/command-line-switches-for-microsoft-office-products-079164cd-4ef5-4178-b235-441737deb3a6

Is there an equivalent switch for NetOffice?  Automation of repetitive tasks are greatly slowed by heavy add-in users :(

**Comment by jozefizso** [comment]
Hi @callidex,
I could not find any option to create application instance with add-ins loading disabled. When addin is loaded, it can check if Office app is running in automation mode and it can stop executing itself. This depends on the addin implementation tough.

You can also disable add-ins manually by changing `LoadBehavior` in registry and run automation code afterwards.

**Comment by jozefizso** [comment]
Or you can start Word using the `winword.exe /a` parameter and connect to the running instance afterwards.
