### ISSUE TITLE
NetOffice.WordApi wdFieldFormTextInput truncates over 255 characters

### ISSUE THREAD

**Issue by pattyk13** [NetOfficeFw/NetOffice#294]
Hello, 

I recently switched from interop to NetOfficeFw in hopes that it would have fixed some of the limitations in creating a word document.  I have this code:

            Word.FormField formField = document.FormFields.Add(range, Word.Enums.WdFieldType.wdFieldFormTextInput);

            formField.TextInput.Default = defaultText;
            formField.TextInput.EditType(Word.Enums.WdTextFormFieldType.wdRegularText);

It works great except of the defaultText is over 255 characters, and then it truncations to 255. 

Thanks in advance.

**Comment by jozefizso** [comment]
Hi @pattyk13, does this truncation occur when you use the Interop directly?

**Comment by jozefizso** [comment]
**API Reference**

[FormField.TextInput property (Word)](https://docs.microsoft.com/en-us/office/vba/api/word.formfield.textinput)  
[TextInput.Default property (Word)](https://docs.microsoft.com/en-us/office/vba/api/word.textinput.default)


**TextInput.Default property** returns or sets the text that represents the default text box contents. Read/write String.

**Comment by jozefizso** [comment]
When I enter the default text value in the **Text Form Field Options** dialog, it is truncated to the 255 characters.

Entered value: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dapibus tincidunt sapien ac varius. Proin egestas erat nec fermentum pretium. Nunc id nisi non diam imperdiet venenatis. Suspendisse iaculis massa sit amet imperdiet dictum. Morbi suscipit est non risus cursus, porta sagittis mi augue.` (300 characters)

Accepted value: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dapibus tincidunt sapien ac varius. Proin egestas erat nec fermentum pretium. Nunc id nisi non diam imperdiet venenatis. Suspendisse iaculis massa sit amet imperdiet dictum. Morbi suscipit e` (255 charaters)

![image](https://user-images.githubusercontent.com/287778/92274544-be902900-eeed-11ea-8e65-56b61b53c861.png)

**Comment by jozefizso** [comment]
This is behavior of Microsoft Word. It is limiting the `TextInput.Default` value to 255 characters.

**Comment by pattyk13** [comment]
Yes.
