### ISSUE TITLE
Can we create a VB.Net dll compatible with Microsoft Access with NetOffice ?

### ISSUE THREAD

**Issue by Xaalek** [NetOfficeFw/NetOffice#299]
Can we create a VB.Net dll compatible with Microsoft Access with NetOffice ?

**Comment by jozefizso** [comment]
Hi @Xaalek, can you clarify your feature request in more detail?

NetOffice can be used to work with MS Access even when you code in Visual Basic .NET. Use the [NetOfficeFw.Access](https://www.nuget.org/packages/NetOfficeFw.Access/1.7.8) package.

**Comment by Xaalek** [comment]
I would like to create a .Net dll and use it in MS Access without using "register for COM interop". I need to use .Net dll without being an admin on the pc. Is it possible with NetOffice ?

**Comment by jozefizso** [comment]
Yes, you can do that with NetOffice. Create an addin project for Microsoft Access.

You must register your assembly for COM, other Access won't be able to use the addin.

The assembly can be registered in COM without administrator rights. This can be done with the **RegAddin** application, or by creating all the registry keys manually.

**Comment by Xaalek** [comment]
Yeah, but I don’t want it to register in the registry

**Comment by jozefizso** [comment]
It is a requirement to register the assembly in COM registry to create an addin for Microsoft Office applications.

**Comment by Xaalek** [comment]
Ok but we can register dll in visual studio without NetOffice. I don't understand the usefulness of NetOffice

**Comment by jozefizso** [comment]
It has great documentation for MS Office APIs, it works with any Office version and there are great utility methods which make it easier to create addins for MS Office.

**Comment by Xaalek** [comment]
Ok thank you for this clarification
