### ISSUE TITLE
I need to save excel to PDF

### ISSUE THREAD

**Issue by abinscjames** [NetOfficeFw/NetOffice#301]
Dear,

I am trying to save modified excel to pdf. In word API i could see that we have a method "SaveAs2". But in excelApi, i couldn't find it.

Can any one provide me details.

Thanks in advance.

**Comment by jozefizso** [comment]
Hi @abinscjames, use the `Workbook.SaveAs()` method.

https://docs.microsoft.com/en-us/office/vba/api/excel.workbook.saveas

**Comment by abinscjames** [comment]
When tried SaveAs(), the output file i receive
[6b77d357ae6443feabdb0dea14ed3b5f.pdf](https://github.com/NetOfficeFw/NetOffice/files/5297957/6b77d357ae6443feabdb0dea14ed3b5f.pdf)
 is corrupted.

![image](https://user-images.githubusercontent.com/66824903/94541374-24f63600-0265-11eb-963e-73d18ac38c9a.png)

**Comment by jozefizso** [comment]
The file you provided is an Excel file in XLSX format, not a PDF.

Try to use the `Workbook.ExportAsFixedFormat` with `XlFixedFormatType.xlTypePDF` type set.

https://docs.microsoft.com/en-us/office/vba/api/excel.workbook.exportasfixedformat

Sample: https://exceloffthegrid.com/vba-code-save-excel-file-as-pdf/
