### ISSUE TITLE
Password limits for Office 2016 and earlier.

### ISSUE THREAD

**Issue by dtakemori-jsc** [NetOfficeFw/NetOffice#309]
Thank you very much for your help.
When I open a file in Word and Excel before Office 2016, if the password is more than 16 characters, I can't open it, is there a character limit?

**Comment by jozefizso** [comment]
hi @dtakemori-jsc, this is a question for the Microsoft product team: https://docs.microsoft.com/en-us/office/vba/articles/feedback-support
