### ISSUE TITLE
PowerPointApi.Application events not working

### ISSUE THREAD

**Issue by Eraser3** [NetOfficeFw/NetOffice#312]
I installed NetOffice.PowerPoint.Net45 version 1.7.4.11 trough the Visual Studio 2019 NuGet package manager and created a simple project. I want to know when a slideshow begins and when PowerPoint moves to the next or previous slide.

The following events do not seem to fire at all:
`SlideShowBeginEvent`
`SlideShowNextSlideEvent`
`SlideShowOnNextEvent`
`SlideShowOnPreviousEvent`

I then reverted to version 1.7.4.4. That fixed two events for me but the `SlideShowOnNextEvent` and `SlideShowOnPreviousEvent` events still didn't fire. The `SlideShowNextSlideEvent` event fires for when we move to the next or previous slide.

**Comment by jozefizso** [comment]
Hi @Eraser3,
the `NetOffice.PowerPoint.Net45` package and other packages on nuget under the organization "netofficedotnet" does not work in release 1.7.4.11. That's incorrect release (see #276) and you must change your project to use [NetOfficeFw.PowerPoint](https://www.nuget.org/packages/NetOfficeFw.PowerPoint/)

[These packages](https://www.nuget.org/profiles/netoffice) will work correctly and they have all the latest bug fixes, including the bugs in these events in PowerPoint library (#262).

**Comment by jozefizso** [comment]
Please, reopen the issue if this does not solve your problem.
