### ISSUE TITLE
Failed to proceed PropertySet on PowerPoint.ParagraphFormat=>Alignment.

### ISSUE THREAD

**Issue by kevin-vanderwende** [NetOfficeFw/NetOffice#317]
I have an app that takes multiple PowerPoint files into one presentation.  I have experienced issues with "Failed to proceed..." on several things.  The way I have mitigated this was I put in a sleep function with a configurable duration to slow things down.  I had noticed that I was having slides added in the wrong place which meant my merging was going too fast and I needed to control that.
I recently added code to add text to the bottom of a slide.  If I set my delay high enough I don't run into the PropertySet error but it is inconsistent.  Sometimes it works with a delay of 250ms.  Sometimes it fails with 2500ms.  The code causing the issue is below:
`var txtBox = slide.Shapes.AddTextbox(MsoTextOrientation.msoTextOrientationHorizontal, txtBoxLeft, txtBoxTop, txtBoxSize.Width, txtBoxSize.Height);
var textRange = txtBox.TextFrame.TextRange;
textRange.ParagraphFormat.Alignment = (PpParagraphAlignment)configSettings.SongSlideFooterTextAlign;`

I tried modifying the DCOM settings I read about in another issue but that didn't change the behavior.

**Comment by jozefizso** [comment]
Is you app using automation to run PowerPoint code, or do you have an Add-in which is running inside PowerPoint?

**Comment by kevin-vanderwende** [comment]
> Is you app using automation to run PowerPoint code, or do you have an Add-in which is running inside PowerPoint?

Automation.  Create a new presentation with window then Copy/Paste with Formatting.

**Comment by jozefizso** [comment]
It is normal for the Office apps to be unresponsive when using automation. As the automation cannot be in sync with the main thread of the Office app, the code will fail more often and you must write a lot of retry logic to make sure the code will get eventually executed.

Adding delays to the code may help, but there is no way to sync the automation code to the main thread of the Office app.

**Comment by kevin-vanderwende** [comment]
Thanks for the information. I will try the retry logic.

**Comment by kevin-vanderwende** [comment]
Turned out I was never initializing my align option that I store in app.config so when I tried to set TextRange.ParagraphFormat.Alignment I was using in invalid value.  The enum PpParagraphAlignment has -2 and 1-7.  I was attempting to set it to 0.  The reason it seemed intermittent is I would change the setting then run and it would work.  Close the app and reopen and it reset to 0.

**Comment by kevin-vanderwende** [comment]
I've been meaning to close the loop on this.  I've just recently updated my code. jozefizso was correct about retry logic.  I added Polly to my project and implemented WaitAndRetry to only alert the user that something went wrong after a configured number of retries.  I have not had any transient exceptions thrown as a message box since.

Thanks so much.
