### ISSUE TITLE
Add net5.0-windows moniker to TargetFrameworks

### ISSUE THREAD

**Issue by michaeloyer** [NetOfficeFw/NetOffice#319]
Today it looks we can use .NET 5, with the following project file `App.fsproj`:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetOfficeFw.Excel" Version="1.8.1" />
    <PackageReference Include="NetOfficeFw.Core" Version="1.8.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

And `Program.fs`:

```
open NetOffice.ExcelApi

[<EntryPoint>]
let main _ =
    use app = new Application(Visible=true)
    use workbook = app.Workbooks.Add()
    use worksheet = workbook.Worksheets.Add() :?> Worksheet
    worksheet.Range("A1").Value2 <- 1;

    0
```

Right now it generates a lot of compiler warnings about being targeted to various .NET Framework versions, but it's usable, at least with the little bit of testing I've done. Not sure if you can have it target WinForms in someway though.

**Comment by jozefizso** [comment]
Hi @michaeloyer, yes, in general you can use existing NetOffice libraries with the .NET Core when you target Windows platform only.

Although there was some work done to add support for .NET Core 3 and it should be updated for .NET 5, I have only a little spare time to prepare such release compared to the benefits as current packages should be fully usable with those TFMs.

**Comment by michaeloyer** [comment]
Ah that makes sense. I had seen the issue for .NET Core 3, but I assumed that .NET 5 (windows) would be more of a straight forward upgrade than .NET Core. After posting I checked out the project files and realized that the .NET Framework project file didn't make that possible. I see too you already did the necessary work to make adding .NET 5 or 6 pretty simple at [33f8d20](https://github.com/NetOfficeFw/NetOffice/commit/33f8d204a2a10b8435e7b38b79ffeaf1a9b83fdc). I apologize for adding to the noise for something you already have covered. Thanks! 👍
