### ISSUE TITLE
Net Core 6 preview

### ISSUE THREAD

**Issue by lorinkundert** [NetOfficeFw/NetOffice#322]
I have not found any real issues with this working under a pure Net Core 6 project except for one, if compiled as a single file app the error is :  System.ApplicationException: Process_MSWord_Documents
 ---> System.Exception: MSDOC
 ---> System.AggregateException: One or more errors occurred. (CodeBase is not supported on assemblies loaded from a single-file bundle.)
 ---> System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.

If I package it normally with all dependencies outside of the exe, it works fine, I would suspect that once you have Net Core 3.1 available that might go away.

**Comment by ApolonTorq** [comment]
I haven't used NetOffice but will likely do so in the next few months. Ideally this would eventually lead to using it with .NET 6.0.

@lorinkundert Do you compile the NetOffice source code from scratch in a forked repo to be able to work under a "pure Net Core 6" project? Or is the reference to "Net core 6" a NetOffice version reference and nothing to do with Microsoft .NET?

**Comment by jozefizso** [comment]
Hi, we will have the package with support for .NET Core 3.1 LTS and .NET 6.0 LTS ready soon. The package will support only Windows (eg. `net6.0-windows` TFM) and it won't be a cross platform library.

**Comment by ApolonTorq** [comment]
> Hi, we will have the package with support for .NET Core 3.1 LTS and .NET 6.0 LTS ready soon.

Brilliant, thanks.

> The package will support only Windows (eg. `net6.0-windows` TFM) and it won't be a cross platform library.

Of course! 😄

**Comment by Kiriller12** [comment]
Hello! Do you have any success with porting to .NET 6 or NET Core 3.1?

**Comment by jozefizso** [comment]
Hi @Kiriller12, the port for .NET 6 is being done on branch https://github.com/NetOfficeFw/NetOffice/tree/dev/net6

**Comment by jozefizso** [comment]
First set of preview packages are published here: https://www.myget.org/gallery/netoffice

They are compiled for .NET Framework 4.6.1, .NET Core 3.1 and .NET 6.

**Comment by jozefizso** [comment]
Closing in favor of #343
