### ISSUE TITLE
Does not work when ran with scheduled tasks

### ISSUE THREAD

**Issue by glautrou** [NetOfficeFw/NetOffice#323]
Hi,

When I execute my program with a **Windows Scheduled Task** the method `Open()` returns `null`.

```
using (var word = new Word.Application())
{ 
    if (!File.Exists(wordFile.FullName)) // => file exists
        throw new FileNotFoundException(wordFile.FullName);

    var document = word.Documents.Open(wordFile.FullName); // => document is null
    if (document == null)
        throw new Exception($"Document null : {wordFile.FullName}"); // => Exception here
}
```

I my scheduled task running under the `administrator` account I checked :
- "Execute even if user is not connected"
- "Execute with maximal authorisations"

It only works if the `administrator `account is logged in, which is not possible to keep on a server, especially after a reboot.
Is it possible to work without active user session?

Thanks for your help.

Note : I am currently using the latest NuGet package : NetOffice.Word 1.7.4.11.

**Comment by jozefizso** [comment]
For questions about system integration and/or implementation for specific use case please post your question to https://stackoverflow.com/ with tag [netoffice]

**Comment by jozefizso** [comment]
PS: our official and digitally signed package is **NetOfficeFw.Word**, latest release 1.8.

The package you are using is a rogue one and it does not work correctly.
