### ISSUE TITLE
[Question] How to open ppt or pptx and export all slides as images

### ISSUE THREAD

**Issue by SID9-HoneyBee** [NetOfficeFw/NetOffice#326]
I want to save every page in a Powerpoint document as individual images.
Is there a function to export slides as images?

If yes, how should I use it?

And is it still not available in Net5?

**Comment by jozefizso** [comment]
Hi, as you can do this in the PowerPoint itself, it can be implement using PowerPoint automation. A sample code: https://www.free-power-point-templates.com/articles/using-vba-to-export-powerpoint-slides-to-images/

PS: these types of questions are better asked on https://stackoverflow.com/ with the tag `[netoffice]`.
