### ISSUE TITLE
Group method for Range fails with MethodCOMException

### ISSUE THREAD

**Issue by IainDM** [NetOfficeFw/NetOffice#328]
Hi

I am trying to group 5 rows on a worksheet - let's say rows 6-10. I use Range("A6:A10").EntireRow.Group(). This works just fine using InterOp but fails with a MethodCOMException using NetOffice. 

From the source, it looks like only the Group methods for PivotTables are implemented. Is this right?

Thanks!

**Comment by samatrhea** [comment]
I typically use the `OutlineLevel` property to apply grouping. Your code should look something like  `Range("A6:A10").EntireRow.OutlineLevel = 1`.

**Comment by IainDM** [comment]
thanks!
