### ISSUE TITLE
Core DisposeAllComProxies throws if underlying object has been closed by user

### ISSUE THREAD

**Issue by IainDM** [NetOfficeFw/NetOffice#329]
Here's the situation:
1.  I have an addin which creates an Excel workbook.
2. The addin keeps a reference to the workbook in case it needs to update it in future.
3. When the addin closes, it calls Core.Default.DisposeAllCOMProxies to make sure everything is tidied up.

But, if the user closes the workbook manually, between 2 and 3 above, the DisposeAllCOMProxies in step 3 throws an Exception because the "COMObject has been separated from its underlying RCW".

**Comment by jozefizso** [comment]
You should clean up resources when the workbook is closed. Otherwise you are holding references to non existing COM objects.
