### ISSUE TITLE
NetOffice.OutlookApi.NameSpace.RemoveStore() function not found

### ISSUE THREAD

**Issue by ryangriggs** [NetOfficeFw/NetOffice#333]
NetVersion 1.8.1
I see the function declaration in https://github.com/NetOfficeFw/NetOffice/blob/603f7f5fd010f0055570a460e0cdc63b6ef60425/Source/Outlook/DispatchInterfaces/_NameSpace.cs#L616

But it yields the error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'_NameSpace' does not contain a definition for 'removeStore' and no accessible extension method 'removeStore' accepting a first argument of type '_NameSpace' could be found (are you missing a using directive or an assembly reference?)	test	D:\My Documents\Programming\test\V1\test\Form1.cs	52	Active

How to fix this?

Thanks!

**Comment by jozefizso** [comment]
Released in v1.9.0
