### ISSUE TITLE
Outlook attachment

### ISSUE THREAD

**Issue by eduardomrp** [NetOfficeFw/NetOffice#339]
Hello!

Outlook attachment location in NetOffice is different from the location of Outlook: the attachment is placed on the body.
See the pictures (first is via netoffice, the second is via Outlook)

With this method the user delete the attachement when writing

Can we change this ?

![Via_NetOffice](https://user-images.githubusercontent.com/8831850/149828349-fdde2a53-ca90-49aa-b9f2-1d2b3d3197d5.jpg)
![Via_Outlook](https://user-images.githubusercontent.com/8831850/149828353-043b8b23-c1f7-4e63-9268-40dff4706b32.jpg)

**Comment by jozefizso** [comment]
Hi @eduardomrp,
please read the [Attach a File to an Outlook Email Message
](https://docs.microsoft.com/en-us/office/vba/outlook/concepts/attachments/attach-a-file-to-an-outlook-email-message).

For questions about using Office API please ask questions on [stackoverflow.com](https://stackoverflow.com/) with the tag `[netoffice]` or check the [Office VBA support](https://docs.microsoft.com/en-us/office/vba/articles/feedback-support) page.

**Comment by eduardomrp** [comment]
Thanks!

body format must be HTML for placement on image2
