### ISSUE TITLE
does this support unity

### ISSUE THREAD

**Issue by BonnyShen** [NetOfficeFw/NetOffice#340]
Im using unity to develop a tool with ppt parsing.
I changed unity api to .net 4x and add `NetOffice.dll, OfficeApi.dll, PowerPointApi.dll, VBIDEApi.dll, stdole.dll`.
when I call `PowerPoint.Application app = new PowerPoint.Application();` 
I got the error: `NotImplementedException: Unmanaged activation is not supported`.
so the netoffice is not support unity now?

**Comment by jozefizso** [comment]
Hi @BonnyShen, please, contact the Unity support.

NetOffice supports the .NET Framework on Windows OS.
