### ISSUE TITLE
Cannot create taskpane for Word - Word sample 

### ISSUE THREAD

**Issue by ashishpCACTUS** [NetOfficeFw/NetOffice#347]
Hi Jozef, 

I tried using the sample '02 NetOffice Word COMAddin Sample' with 1.7.8 version. But the task pane doesnt appear. 

I also looked at some changes listed here - https://github.com/NetOfficeFw/NetOffice/issues/280 namely adding the ProgId, ComVisible, Guid to the SampleControl class. 

Below is my configuration - 

1. Addin

```
   [COMAddin("Word02 Sample Addin CS4", "Ribbons & Panes Addin Example", 3)]
    [ProgId("Word02AddinCS4.Connect"), Guid("E7E8652F-7F9C-48E5-BC7A-7CD5375057AB")]
    [CustomUI("RibbonUI.xml", true)]
    [CustomPane(typeof(SamplePane), "Word CPU Usage", false, PaneDockPosition.msoCTPDockPositionRight, PaneDockPositionRestrict.msoCTPDockPositionRestrictNoChange, 100, 100)]
    public class Addin : COMAddin
```
    
<img width="1632" alt="image" src="https://user-images.githubusercontent.com/49706779/170235352-8e0ee975-ad1f-43ff-a7f6-81c27651b33f.png">

2. SampleControl

```
  [ComVisible(true)]
    [Guid("E3D5658F-B3B7-41F5-9452-A4AD07652C44")]
    [ProgId("Word02AddinCS4.SamplePane")]
    public partial class SamplePane : UserControl, NetOffice.WordApi.Tools.ITaskPane
```

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/49706779/170235568-4f78123c-338b-47d1-b99e-e44409390ede.png">

3. Registered the addin 

![image](https://user-images.githubusercontent.com/49706779/170235877-09aa8d4b-e23a-4a62-a887-f49f9b75acbf.png)

4. I can see both of them are Com enabled
![image](https://user-images.githubusercontent.com/49706779/170236184-036f5d64-944a-477f-9682-acff07ccb8f9.png)

5. But still the Taskpane doesnt appear
![image](https://user-images.githubusercontent.com/49706779/170236484-a73ee55e-5c78-4245-a2b7-f3eaf186afe0.png)

On debugging I cant see any error. It sets the visibility of the user control but nothing happens post that. Should i check error somewhere else. Or this could be a case for this https://github.com/NetOfficeFw/NetOffice/issues/271 

System configuration; 
Base system - MacBook pro Apple M1 - MacOS Monterey - Version 12.3.1

Windows hosted using Parallel Desktop - 17.1.2
VS 2019 community edition
Window 11 - 22H2 OS Build 22621.1
Word - Microsoft 356 - version 2204

I would appreciate help as we would like to create word addins which are Word version agnostic and i could see NetOffice as the best option. Thanks for such a great product. Let me know if any other information needed

**Comment by ashishpCACTUS** [comment]
Hi Jozef,

Any update on this one. 

Thanks,
Ashish Padhy

**Comment by jozefizso** [comment]
Hi @ashishpCACTUS, no update on this one.

**Comment by jozefizso** [comment]
Closing this issue as the Word samples for task panes work correctly and we have a production code which works.
