### ISSUE TITLE
The offset property of the Excel Range seems to be wrong

### ISSUE THREAD

**Issue by ksxdhung** [NetOfficeFw/NetOffice#348]
sheet.Range("R5").Offset(0, 4) must return cell V5.
But it returns cell U4.
Please check.

![image](https://user-images.githubusercontent.com/32445328/170397656-9398b8dc-6ce6-4fb3-b139-134fb213cb84.png)

![image](https://user-images.githubusercontent.com/32445328/170397160-ac16fc88-e16a-4b7d-ac58-190bc143dd90.png)

**Comment by jozefizso** [comment]
Please provide more information about the problem, especially reproducible code.
