### ISSUE TITLE
Workbook class missing AutoSaveOn property

### ISSUE THREAD

**Issue by IainDM** [NetOfficeFw/NetOffice#349]
https://docs.microsoft.com/en-us/office/vba/api/excel.workbook.autosaveon

**Comment by IainDM** [comment]
It looked like a change to _Workbook.cs would do the trick. Something like the code below. but I am new to NetOffice so I'm unsure!

	public bool AutoSaveOn
		{
			get
			{
				return Factory.ExecuteBoolPropertyGet(this, "AutoSaveOn");
			}
			set
			{
				Factory.ExecuteValuePropertySet(this, "AutoSaveOn", value);
			}
		}

**Comment by jozefizso** [comment]
This property is available in **Microsoft Office 2016, version 2004 (build 12730.20352)**

I did not update NetOffice with API from this build yet.

**Comment by jozefizso** [comment]
Released in v1.9.0
