### ISSUE TITLE
NetOffice.OutlookSecurity

### ISSUE THREAD

**Issue by 21r8390** [NetOfficeFw/NetOffice#350]
I am in the process of upgrading an old project to a newer NET version. So far I have been using DLLs, however I now want to use NuGet for versioning. Unfortunately I can't find a way to suppress OutlookSecurity. Is this no longer necessary or is there another way?

See old docs: https://netoffice.io/toolbox/outlook_security.html

This code does not work anymore:
```csharp
public void Foo()
{
    NetOffice.OutlookSecurity.Supress.Enabled = true;
}
```

Im using these NuGet package:
- NetOfficeFw.Outlook
- NetOfficeFw.Core

**Comment by jozefizso** [comment]
Hi @21r8390, this functionality was removed a long time ago. See #67

**Comment by 21r8390** [comment]
Didn't saw that coming! 😂🥴 Thx
