### ISSUE TITLE
Enumerating DAO Recordset Fields throws 'Class does not exist: NetOffice.DAOApi.Field3'

### ISSUE THREAD

**Issue by shoderico** [NetOfficeFw/NetOffice#351]
MS Introduce new 'Field3' class.
https://stackoverflow.com/questions/72831316/
Please support this class.

**Comment by shoderico** [comment]
I made a pull-request.
https://github.com/NetOfficeFw/NetOffice/pull/352

Please consider to merge it.
Regards

**Comment by jozefizso** [comment]
Hi @shoderico, can you try this build with the `Field3` class implemented?

https://github.com/NetOfficeFw/NetOffice/actions/runs/3136555231
