### ISSUE TITLE
Problem migrating to NetofficeFW

### ISSUE THREAD

**Issue by ilens** [NetOfficeFw/NetOffice#353]
I have removed fhe old references NetOffice v1.7 from my project and used the Package Manager to install NetofficeFW v 1.8.1
I have then changed "Imports excel=Netoffice.excel" to "Imports excel=NetofficeFW.excelAPI"  but Visual Studio says that this Type does not include any public members or cannot be found. The project file includes the statements
  <Reference Include="ExcelApi, Version=1.7.3.0, Culture=neutral, PublicKeyToken=0b8d9ba5199d6dcb, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <HintPath>..\PCS_Structure\packages\NetOfficeFw.Excel.1.8.1\lib\net40\ExcelApi.dll</HintPath>
    </Reference>
and the dll exists at that location. 

The NuGet package manager also shows tha package is installed

What have I done wrong?

**Comment by jozefizso** [comment]
Please, learn about using packages in Visual Studio. This is out of scope of this project.
