### ISSUE TITLE
Please add Shape.IsNarration to PowerPointApi

### ISSUE THREAD

**Issue by ICompareSolutions** [NetOfficeFw/NetOffice#355]
Please add Shape.IsNarration property to PowerPointApi.  It is available in the COM API, but not in Microsoft .NET office interop API.  (Not sure why).

This code works...

        /// <summary>
        /// SupportByVersion PowerPoint 9, 10, 11, 12, 14, 15, 16
        /// Get/Set
        /// </summary>
        /// <remarks> Docs: <see href="https://docs.microsoft.com/en-us/office/vba/api/PowerPoint.Shape.IsNarration"/> </remarks>
        [SupportByVersion("PowerPoint", 9, 10, 11, 12, 14, 15, 16)]
        public NetOffice.OfficeApi.Enums.MsoTriState IsNarration
        {
            get
            {
                return Factory.ExecuteEnumPropertyGet<NetOffice.OfficeApi.Enums.MsoTriState>(this, "IsNarration");
            }
            set
            {
                Factory.ExecuteEnumPropertySet(this, "IsNarration", value);
            }
        }

**Comment by jozefizso** [comment]
This member was added in Microsoft Office 2016, version 2004 (build 12730.20352) and NetOffice was not updated yet for that release.

**Comment by jozefizso** [comment]
Released in v1.9.0
