### ISSUE TITLE
ExcelAPI - Exeption accessing null cell

### ISSUE THREAD

**Issue by ilens** [NetOfficeFw/NetOffice#359]
The VB.Net statement "currWS.Cells(currRow, col).Text Is Nothing" gives the following if the cell is empty (null)...

'currWS.Cells(currRow, col)' threw an exception of type 'NetOffice.Exceptions.PropertyGetCOMException'
    Data: {System.Collections.ListDictionaryInternal}
    ErrorCode: -2147467259
    HResult: -2147467259
    HelpLink: Nothing
    InnerException: {"Exception has been thrown by the target of an invocation."}
    Message: "Failed to proceed PropertyGet on Excel.Range=>_Default."
    Source: "NetOffice"
    StackTrace: "   at NetOffice.Invoker.PropertyGet(ICOMObject comObject, String name, Object[] paramsArray)" & vbCrLf & "   at NetOffice.CorePropertyGetExtensions.ExecuteKnownReferencePropertyGetInternal[T](Core value, ICOMObject caller, String name, Type knownType, Object[] validatedArgs)" & vbCrLf & "   at NetOffice.CorePropertyGetExtensions.ExecuteKnownReferencePropertyGet[T](Core value, ICOMObject caller, String name, Type knownType, Object argument1, Object argument2)" & vbCrLf & "   at NetOffice.ExcelApi.Range.get_Item(Object rowIndex, Object columnIndex)"
    TargetSite: {System.Object PropertyGet(NetOffice.ICOMObject, System.String, System.Object[])}

It works OK if the cell is not null

How do get round this fix this? (NetOffice version 1.8.1.0)

**Comment by jozefizso** [comment]
For questions about using Office API please ask questions on [stackoverflow.com](https://stackoverflow.com/) with the tag [netoffice] or check the [Office VBA support](https://docs.microsoft.com/en-us/office/vba/articles/feedback-support) page.

**Comment by ilens** [comment]
Ignore this - user error!!!

**Comment by ilens** [comment]
Ignore this - user error!!!
