### ISSUE TITLE
Offset behavior - 0/1 bug?

### ISSUE THREAD

**Issue by IainDM** [NetOfficeFw/NetOffice#366]
suppose I have a variable Range baseRange, which points to cell E10. Then baseRange.Offset[0,0] should also point to E10. But it points to D9.

**Comment by jozefizso** [comment]
Indexing in macros, Visual Basic and Office APIs are 1 based.

**Comment by IainDM** [comment]
Yes, I agree, that's true for indexes for methods like Cell[x,y]. But not for Offset.

For example:

Using the Office Interop Assemblies, Range["A1"].Offset[0, 0].Address = "$A$1"
In VBA, MsgBox Range("b5").Offset(0, 0).Address  shows a message box with $B$5

**Comment by IainDM** [comment]
See also VBA help: https://learn.microsoft.com/en-us/office/vba/api/Excel.Range.Offset

**Comment by jozefizso** [comment]
https://github.com/NetOfficeFw/NetOffice/issues/177#issuecomment-646313156

**Comment by IainDM** [comment]
@jozefizso thank you.
