### ISSUE TITLE
Clarification on upgrade from 1.8.1 to 1.9.0 nuget packages

### ISSUE THREAD

**Issue by jimfoye** [NetOfficeFw/NetOffice#367]
I use NetOffice for Outlook and deploy the four assemblies as stated in the documentation. I am confused by what I'm seeing when I attempt to update via nuget from 1.8.1 to 1.9.0.

![image](https://user-images.githubusercontent.com/4249676/195222363-bd201231-a4ed-4ce5-9607-e09ce60d736d.png)

First, since deployment requirements haven't changed for Outlook (I don't think), why is the additional NetOffice package being pulled in? Second, why is the stdole package being pulled in? I have read

https://github.com/NetOfficeFw/NetOffice/issues/316

which states that stdole is already everywhere and should not be deployed with the application, but doesn't explain why all of a sudden it's a required nuget package.

For an extra bit of weirdness, as soon as I'm done with this upgrade, nuget wants me to update the stdole package from 7.0.33 to 17.3.32804.24 (!).

**Comment by jozefizso** [comment]
Hi @jimfoye, as NetOffice packages are now built using `dotnet pack` each project has it's own package now. Before, the base `NetOfficeFw.Core` package contained three libraries: `NetOffice.dll`, `OfficeApi.dll` and `VBIDEApi.dll`

See https://github.com/NetOfficeFw/Packages/blob/master/src/NetOfficeFw.Core.nuspec

So 1.9 will install some new packages now. The set of assemblies you have to install and distribute with your app is the same.

I did not notice the **stdole** package will be upgraded right away. It should be safe to upgrade it. The library is installed for development only and at the runtime you should use the one available on the system.

Thanks for the feedback. I will look into the **stdole** if this can be improved and perhaps reference the latest version from NetOffice.

Did you notice some issues with the application after upgrade or is it just the new packages structure?
