### ISSUE TITLE
Assemblies in Version 1.9 are not digitally signed

### ISSUE THREAD

**Issue by morgars** [NetOfficeFw/NetOffice#369]
Why are the assemblies in the nuget-Package are not longer digitally signed?
e.g. https://www.nuget.org/packages/NetOfficeFw.Core

**Comment by jozefizso** [comment]
Hi @morgars, thanks for noticing this. I checked the signing pipeline several times before releasing 1.9 so this looks like a bug in the build script.

All assemblies and nuget packages should be signed.

**Comment by morgars** [comment]
Ok, thanks for the reply. 
Then I wait for the fix of the problem.

**Comment by jozefizso** [comment]
I see the problem now. The build script is not signing the assemblies in the individual project output, but in the shared output at `Source\ClientApplication\bin`. So the `dotnet pack` will use the unsinged assemblies.

**Comment by jozefizso** [comment]
Fixed in 1.9.1

![image](https://user-images.githubusercontent.com/287778/198118491-12daea77-ec50-405e-830f-6d60ae4b3b80.png)

**Comment by morgars** [comment]
Hi @jozefizso,
thank you for the quick fix and the great work.
