### ISSUE TITLE
Create setup file for a .netoffice project in advance installer

### ISSUE THREAD

**Issue by je30ca** [NetOfficeFw/NetOffice#373]
my project is a addin word with .netoffice. I tried to create a setup file with advance installer,
The dlls of the debug file are registered, and I gave administrator access for run setup

But still my addin is not loaded in Word!
Can anyone help?

Do I have to dll register in another way? Or should I do something else?

**Comment by jozefizso** [comment]
hi @je30ca, you must register you addin assemblies. Please, refer to the Microsoft documentation:

https://learn.microsoft.com/en-us/previous-versions/office/troubleshoot/office-developer/office-com-add-in-using-visual-c
https://learn.microsoft.com/en-us/visualstudio/vsto/developing-office-solutions?view=vs-2022

**Comment by jozefizso** [comment]
Hi, I do not provide support for 3rd party tools.
