### ISSUE TITLE
Is NetOffice supports multithreading?

### ISSUE THREAD

**Issue by oleh-yashchyshyn-agiliway** [NetOfficeFw/NetOffice#393]
I am using NetOfficeFw.Word and I am wondering is NetOfficeFw.Word supports multithreading? 

Because, as I know, Interop objects are not multithreading.

**Comment by oleh-yashchyshyn-agiliway** [comment]
@jozefizso I am using it in WPF application. Could you please suggest better approach then using Dispatcher in order to invoke on main thread?

**Comment by jozefizso** [comment]
> @jozefizso I am using it in WPF application. Could you please suggest better approach then using Dispatcher in order to invoke on main thread?

You must use Dispatcher.

**Comment by oleh-yashchyshyn-agiliway** [comment]
@jozefizso Thank you
