### ISSUE TITLE
Running netoffice in windows service

### ISSUE THREAD

**Issue by chandraarora** [NetOfficeFw/NetOffice#395]
Hi 

I have a question here if it will be possible to run in the windows service or it should be run always as console application or windows form.

Thanks
Chandra

**Comment by jozefizso** [comment]
Yes, you can use NetOffice libraries in a Windows Service host. Keep in mind this requires special configuration of the service to be able to run Microsoft Office COM objects and the apps.

Please, refer to Microsoft documentation about the issue.

**Comment by chandraarora** [comment]
Thank you for your reply, do you have documentation link for Microsoft com object on server side?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jozefizso** [comment]
https://support.microsoft.com/en-us/topic/considerations-for-server-side-automation-of-office-48bcfe93-8a89-47f1-0bce-017433ad79e2

**Comment by chandraarora** [comment]
Thank you. We are ready to pay if it is possible to guide and make it running for server and we have also issues when we have high load of conversion then it stops working, we have queue where it should pickup and convert min 4 workers

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jozefizso** [comment]
Please, write me at jozef@goit.sk
