### ISSUE TITLE
Outlook add-in. Saving mail into file

### ISSUE THREAD

**Issue by VolodymyrMoldovan** [NetOfficeFw/NetOffice#397]
Hi!

I get an random error message
![image](https://github.com/NetOfficeFw/NetOffice/assets/5681660/346bd7cb-a7fc-4376-99df-dd3da4e52ec3)

for the following code

var guid = Guid.NewGuid();
string tempFileName = Path.Combine(Path.GetTempPath(), guid.ToString());
tempFileName = Path.ChangeExtension(tempFileName, ".tmp");
mailitem.SaveAs(tempFileName, OlSaveAsType.olMSGUnicode);
var bytes = File.ReadAllBytes(tempFileName);
if (File.Exists(tempFileName))
{
	File.Delete(tempFileName);
}
return Convert.ToBase64String(bytes);

Thanks
Volodymyr

**Comment by jozefizso** [comment]
I'm sorry but this report is not actionable.

You must provide examples and errors message in English language. And you mis provide a relevant code which doesn't work - ideally a code which reproduces the bug.
