### ISSUE TITLE
PowerPoint.ReadOnlyRecommended missing

### ISSUE THREAD

**Issue by robertmuehsig** [NetOfficeFw/NetOffice#411]
This property is missing in NetOffice: `Presentation.ReadOnlyRecommended`

https://learn.microsoft.com/en-us/office/vba/api/powerpoint.presentation.readonlyrecommended

It seems this thing came with Office 2019 (e.g. see the [OpenXml Remarks](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.office2019.presentation.readonlyrecommended?view=openxml-3.0.1).

As a workaround I used this:

```
 try
 {
     // OfficeInstance == Presentation
     bool isReadOnlyRecommended = OfficeInstance.Property<bool>("ReadOnlyRecommended");
     if (isReadOnlyRecommended)
     {
         return true;
     }
 }
 catch (PropertyGetCOMException)
 {
     // ignore, might happen on pre Office 2019 versions
 }
```

If you wonder where to enable this - here:

![image](https://github.com/NetOfficeFw/NetOffice/assets/756703/e3102aff-36a2-421c-a463-200475698953)

**Comment by jozefizso** [comment]
Hi @robertmuehsig , well, this took unnecessary long time to release, I am sorry for that.

Mostly because I did not have availabel new signing certificate and to get the private preview of the Azure Trusted Signing service it took 6 months from requesting it in January.

**Comment by jozefizso** [comment]
This is not part of the v1.9.6 release.
