### ISSUE TITLE
IExtensibility COMAddin Outlook

### ISSUE THREAD

**Issue by guzman-rc** [NetOfficeFw/NetOffice#412]
I need to create a COM Addin for Outlook and I am using the example: IExtensibility COMAddin Examples (ClassicUI)
but I can't get Outlook to load the DLL. 

I am using Visual Studio 2015 with C#.

The project compiles successfully and the following files are created:
![image](https://github.com/NetOfficeFw/NetOffice/assets/96702862/c0364e9d-10f9-4348-832c-cfec04a22647)

Register the DLL with the command:
![image](https://github.com/NetOfficeFw/NetOffice/assets/96702862/ed2fb509-ee11-4f78-83ff-23144f19f570)

But when I start Outlook the DLL does not load because of a runtime error:
![image](https://github.com/NetOfficeFw/NetOffice/assets/96702862/763b262a-8103-40e5-af2c-6284278d5783)

I would be grateful if you could help me to solve this problem.

**Comment by jozefizso** [comment]
I am sorry, I don't provide support for runtime activation issues in Office apps.

You can try StackOverflow, Microsoft Support or to troubleshoot the problem yourself based on Microsoft documentation.
