### ISSUE TITLE
Unexpected Package Installation Warning

### ISSUE THREAD

**Issue by InteXX** [NetOfficeFw/NetOffice#425]
I'm getting 4 instances of this warning after I run `Install-Package NetOfficeFw.Outlook`, all indicating Line 1 of my `.vbproj` file, in a new `net8.0-windows7.0` WinForms project:

> Package 'NetOfficeFw.Core 1.9.6' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net8.0-windows7.0'. This package may not be fully compatible with your project.

What must I do to rectify the situation?

**Comment by jozefizso** [comment]
Please, read the documentation.

The NetOffice < 2.0 does not support .NET.

**Comment by InteXX** [comment]
> Please, read the documentation.
>
> The NetOffice < 2.0 does not support .NET.

1. Did you mean to say .NET Core?
2. I'm not finding any documentation. I do see some samples, but they're all for .NET Framework 4.8. Do you have a link that discusses this issue?
