### ISSUE TITLE
Is netoffice supporting Office 2021?

### ISSUE THREAD

**Issue by rec-bln** [NetOfficeFw/NetOffice#430]
Hi,

NetOffice claims to support Office 2010, Office 2013, Office 2016, Office 2019 and Office 365.

What about Office 2021? Is it covered by Office 365 as it's basically the same (just a different license model)?

Thanks,
Benedikt

**Comment by jozefizso** [comment]
Yes, the Office 2021 is fully supported as it is essentially the same API as in 2019 and 365.

**Comment by rec-bln** [comment]
thanks! this can be closed
