### ISSUE TITLE
Clean Code

### ISSUE THREAD

**Issue by rcorredera** [NetOfficeFw/NetOffice#5]
Hi, I work for my company on an Outlook Addin since 4 years, and I just found your project.
I found it very interesting, so I choose to participate.
I invite you to take a look on my fork if you want me to make a pull request.
Thanks

**Comment by jozefizso** [comment]
Hi @rcorredera, thanks for the interest in NetOffice project.

It mostly depends on type of changes to code/projects. I still lack some time to maintain the project - unfortunately I cannot guarantee any release soon.

**Comment by jozefizso** [comment]
Regards your refactoring to C# 6: Sebastian, the developer of NetOffice library, released new version of source code few days ago. I am in the process of integrating it into the repository.

NetOffice library source code is hugely generated by tools in the Toolbox folder. We don't have any documentation how this is done before releasing new NetOffice version :(

This means that any fixes to individual projects will not be preserved upon next release. Updating code style and fixing bugs should happen in template files used to generate NetOffice projects. Also I am not sure about dropping support for older .NET Frameworks - NetOffice is still being compiled for .NET 2.0 which may limit the usage of new C# 6 features.

**Comment by rcorredera** [comment]
Hi, thanks for your reply.

You're right for the .Net 2.0 supports, my branch did not make sense.

I was afraid that the code has been generated :), i'll take a look to DeveloperToolbox solution.

**Comment by jozefizso** [comment]
On the other hand, the current code is not .NET 2.0 complaint and targets .NET 4.0. I am not sure yet what's desired target for next release.

**Comment by rcorredera** [comment]
I maybe have misunderstand something, but I don't see where the Toolbox is generating NetOffice code.

By who and when are generated all projects under Source folder ?
