### ISSUE TITLE
Pre-Compiled Version for .NET Framework 2.0

### ISSUE THREAD

**Issue by DanielKarr87** [NetOfficeFw/NetOffice#6]
Thanks for keeping Track of SebastianDotNet's NetOffice Source for further maintaining. 

Is it possible to get precompiled libraries for .NET Framework 2.0, i tried to set the Project for BASE .NET Framework 2.0 but i ran in a lot of compiling errors. It was beautiful and awesome that SebastianDotNet provided the precompiled libraries in a pack on codeplex. 

Did you know when the "new" version (the real next Version of 1.7.3) will be released on CodePlex or how to get precompiled Version of your Code in .NET Framework 2.0?

**Comment by jozefizso** [comment]
No, the next release of 1.7.4 is developed using .NET 4 and it won't compile for .NET 2.0

We already have 1.7.4-alpha2 and Sebastian is working on it.

**Comment by DanielKarr87** [comment]
Thanks for your information. I set the Framework to 4.0 with the code which is provided here on github. Now i get just a few compiler Errors: 
it seems that i need a "axImp.exe" Application. Just installed the SDKs for Windows 7 and 8.1

I'm using Visual Studio 2013 under Windows 10.

Did you know how to get this file. Here's the error (in German):

Fehler	1	Fehler bei der Aufgabe. "AxImp.exe" wurde nicht gefunden, oder das korrekte Microsoft Windows SDK ist nicht installiert. Die Aufgabe sucht im Unterverzeichnis "bin" des im Wert "InstallationFolder" des Registrierungsschlüssels "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.1A\WinSDK-NetFx40Tools-x86" angegebenen Speicherorts nach "AxImp.exe". Das Problem lässt sich möglicherweise wie folgt beheben: 1) Installieren Sie das Microsoft Windows SDK. 2) Installieren Sie Visual Studio 2010. 3) Legen Sie den obigen Registrierungsschlüssel manuell auf den korrekten Speicherort fest. 4) Übergeben Sie den korrekten Speicherort in den ToolPath-Parameter der Aufgabe.	OfficeApi


it says that under the Reg-Key: "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.1A\WinSDK-NetFx40Tools-x86" there's no "AxImp". I installed the SDK but the error still does exist

**Comment by jozefizso** [comment]
The project works in Visual Studio 2015 Update 3.

The error you get is from MSBuild and indicates issue with your Visual Studio, not the project.

**Comment by DanielKarr87** [comment]
what about Visual Studio 2013? Can i "migrate" it back to VS2013 for compiling? I really need the current Version (in .NET40) as libraries but it didn't work. *cry

**Comment by DanielKarr87** [comment]
Could you provide a compiled version on a hoster?

**Comment by jozefizso** [comment]
You can get the development version of NuGet packages at https://www.myget.org/gallery/netofficefw-dev

Those are compiled from the **develop** branch and are not production ready.
