### ISSUE TITLE
Addional CustomUI for 2007

### ISSUE THREAD

**Issue by maliutin** [NetOfficeFw/NetOffice#8]
Hello

I am writing the add-in for PowerPoint and should support versions 2007-2016.

PowerPoint 2007 works with CustomUI - http://schemas.microsoft.com/office/2006/01/customui

`<customUI xmlns="http://schemas.microsoft.com/office/2006/01/customui" onLoad="Ribbon_Load" >`

PowerPoint 2010 and later can work with CustomUI - http://schemas.microsoft.com/office/2009/07/customui

`<customUI xmlns="http://schemas.microsoft.com/office/2009/07/customui" onLoad="Ribbon_Load">`

But this schema is not loaded by PowerPoint 2007.

In my funciotnlity I can not see different between PowerPoint 2007 and PowerPoint 2010 for tabs functionlity. 
But if there is PowerPoint 2010 we need use the context menu.

Thus. Can a special attribute be added for customUI with PowerPoint 2007? For example `CustomUI2007Attribute`.
In this case we could to use CustomUI2007Attribute and CustomUIAttribute together. I.e. if the current host is PowerPoint 2007 than we load customUI xml from CustomUI2007Attribute and in other case we load from CustomUIAttribute,

**Comment by jozefizso** [comment]
You can get application version from `PowerPointApplication.Version` property and override `GetCustomUI()` method to return different Ribbon XML files for different Office versions.

This way you can implement your own `CustomUI2007Attribute` attribute.

**Comment by maliutin** [comment]
@jozefizso Yes. It works.

Thank you.

P.S. NET 3.5 is no longer supported yet?

**Comment by jozefizso** [comment]
No, latest version is for .NET 4.0 only.

NetOffice 1.7.3 is latest release to support .NET 3.5
