### ISSUE TITLE
Set enforceFIPSPolicy = false

### ISSUE THREAD

**Issue by maliutin** [NetOfficeFw/NetOffice#9]
Hello

How can I set `enforceFIPSPolicy = false` for excel addin which uses NetOffice.

```
<configuration>
    <runtime>
        <enforceFIPSPolicy enabled="false"/>
    </runtime>
</configuration>
```

Can I do it only for my add-in?

**Comment by jozefizso** [comment]
By default MS Office application will run NetOffice addin in the implicit AppDomain for .NET COM classes.
In this scenario you must change the `.config` file for given MS Office application (eg. `WINWORD.EXE.config`) to change .NET behavior.

You `app.config` files from NetOffice addin project will not work.

A workaround is to set machine-wide FIPS policy, or you can write C++ COM wrapper that will instantiate NetOffice addin and will provide custom .NET configuration.
